import type { PhaseId, Email, GameTask, Workstream, Deliverable, Risk, Headline, Client, Lead, PlayerResources, TeamMember, StaffProfile, ContractorProfile, MitigationActionId, QualificationNote, BoardSubmission, TempCapacityAllocation, FeeNegotiation, FeeTerms, NegotiationRound, Toast, FinalOffer, DataroomCategory, DataroomAccessLevel, SPANegotiation, SPARound, SPATerms, GameEvent, BudgetRequest, Buyer, CompetitorThreat } from '../types/game';
import type { WeekResult, PhaseGateResult } from '../engine/weekEngine';
export interface GameStore {
    phase: PhaseId;
    day: number;
    totalDays: number;
    week: number;
    leads: Lead[];
    activeLeadId?: string;
    resources: PlayerResources;
    client: Client;
    team: TeamMember[];
    emails: Email[];
    buyers: Buyer[];
    tasks: GameTask[];
    workstreams: Workstream[];
    deliverables: Deliverable[];
    risks: Risk[];
    events: GameEvent[];
    headlines: Headline[];
    weekSummary: string | null;
    weekHistory: {
        day: number;
        week: number;
        daysAdvanced: number;
        summary: string;
        phase: PhaseId;
    }[];
    isWeekInProgress: boolean;
    playerName: string;
    savedAt: string | null;
    hasSeenOnboarding: boolean;
    gameComplete: boolean;
    collapseReason: string | null;
    collapseHeadline: string | null;
    collapseDescription: string | null;
    lastWeekResult: WeekResult | null;
    phaseGate: PhaseGateResult | null;
    totalBudgetSpent: number;
    phaseBudget: {
        phaseBase: number;
        carryover: number;
    };
    budgetRequests: BudgetRequest[];
    qualificationNotes: QualificationNote[];
    boardSubmission: BoardSubmission | null;
    tempCapacityAllocations: TempCapacityAllocation[];
    feeNegotiation: FeeNegotiation | null;
    agreedFeeTerms: FeeTerms | null;
    competitorThreats: CompetitorThreat[];
    toasts: Toast[];
    finalOffers: FinalOffer[];
    preferredBidderId: string | null;
    spaNegotiation: SPANegotiation | null;
    agreedSPATerms: SPATerms | null;
    dataroomCategories: DataroomCategory[];
    phaseDeadline: number | null;
    pitchDocumentReady: boolean;
    bindingOffersReceived: number;
    unaddressedQACount: number;
    advanceWeek: () => void;
    advancePhase: () => Promise<void>;
    updateResources: (partial: Partial<PlayerResources>) => void;
    markEmailRead: (emailId: string) => void;
    flagEmail: (emailId: string) => void;
    escalateEmail: (emailId: string) => void;
    respondToEmail: (emailId: string, responseId: string) => void;
    startTask: (taskId: string) => void;
    completeTask: (taskId: string) => void;
    mitigateRisk: (riskId: string) => void;
    executeRiskMitigationPlan: (riskId: string, planId: string) => void;
    setPlayerName: (name: string) => void;
    markOnboardingSeen: () => void;
    saveGame: () => void;
    completeGame: () => void;
    dismissWeekSummary: () => void;
    requestBudget: (amount: number, justification: string) => void;
    resolveBudgetRequest: (id: string, approved: boolean, approvedAmount?: number) => void;
    investigateDimension: (leadId: string, dimension: keyof NonNullable<Lead['investigation']>) => void;
    scheduleMeeting: (leadId: string) => void;
    addQualificationNote: (note: Omit<QualificationNote, 'id'>) => void;
    submitBoardRecommendation: (recommendation: BoardSubmission['recommendation'], rationale: string, leadId?: string) => void;
    hireStaffer: (profile: StaffProfile) => void;
    allocateTempCapacity: (taskId: string, profile: ContractorProfile) => void;
    releaseTempCapacity: (allocationId: string) => void;
    presentPitch: () => void;
    startFeeNegotiation: () => void;
    submitFeeRound: (terms: Pick<NegotiationRound, 'playerRetainerType' | 'playerRetainerAmount' | 'playerSuccessFeePercent' | 'playerRatchetEnabled' | 'playerRatchetThresholdEV' | 'playerRatchetBonusPercent'>) => void;
    acceptFeeTerms: () => void;
    executeMitigationAction: (threatId: string, action: MitigationActionId) => void;
    addToast: (message: string, type: Toast['type']) => void;
    removeToast: (id: string) => void;
    setPhaseDeadline: (weeks: number) => void;
    selectPreferredBidder: (buyerId: string) => void;
    setDataroomAccess: (categoryId: string, level: DataroomAccessLevel) => void;
    initSPANegotiation: () => void;
    submitSPARound: (terms: Pick<SPARound, 'playerWarrantyScope' | 'playerWarrantyCap' | 'playerEscrowPercent' | 'playerSpecificIndemnity'>) => void;
    acceptSPATerms: () => void;
}
export declare const useGameStore: import("zustand").UseBoundStore<Omit<import("zustand").StoreApi<GameStore>, "setState" | "persist"> & {
    setState(partial: GameStore | Partial<GameStore> | ((state: GameStore) => GameStore | Partial<GameStore>), replace?: false | undefined): unknown;
    setState(state: GameStore | ((state: GameStore) => GameStore), replace: true): unknown;
    persist: {
        setOptions: (options: Partial<import("zustand/middleware").PersistOptions<GameStore, Record<string, unknown>, unknown>>) => void;
        clearStorage: () => void;
        rehydrate: () => Promise<void> | void;
        hasHydrated: () => boolean;
        onHydrate: (fn: (state: GameStore) => void) => () => void;
        onFinishHydration: (fn: (state: GameStore) => void) => () => void;
        getOptions: () => Partial<import("zustand/middleware").PersistOptions<GameStore, Record<string, unknown>, unknown>>;
    };
}>;
//# sourceMappingURL=gameStore.d.ts.map