import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useGameStore } from '../../store/gameStore';
import { PHASE_NAMES } from '../../types/game';
import { Settings, Bell, Menu, } from 'lucide-react';
import NotificationsPopover from '../NotificationsPopover';
import SettingsModal from '../SettingsModal';
function KpiPill({ label, value, color }) {
    return (_jsxs("div", { className: "flex items-center gap-1.5 px-3 py-1 rounded-[var(--radius-md)] bg-surface-default border border-border-subtle", children: [_jsx("span", { className: "text-[11px] font-mono uppercase tracking-wider text-text-muted", children: label }), _jsx("span", { className: `text-[13px] font-semibold font-mono ${color || 'text-text-primary'}`, children: value })] }));
}
export default function Topbar({ onMenuToggle }) {
    const { phase, day, week, resources, emails } = useGameStore();
    const unreadCount = emails.filter((e) => e.state === 'unread').length;
    const [showNotifications, setShowNotifications] = useState(false);
    const [showSettings, setShowSettings] = useState(false);
    return (_jsxs("header", { className: "h-12 flex items-center justify-between px-4 bg-bg-primary/80 backdrop-blur-sm border-b border-border-subtle shrink-0 z-50", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("button", { onClick: onMenuToggle, className: "lg:hidden p-1.5 rounded-md text-text-muted hover:text-text-primary hover:bg-surface-hover transition-colors", children: _jsx(Menu, { size: 18 }) }), _jsx("h1", { className: "text-[14px] md:text-[15px] font-display font-semibold text-text-accent tracking-wide whitespace-nowrap", children: "THE M&A RAINMAKER" }), _jsxs("div", { className: "hidden md:flex items-center gap-3", children: [_jsx("div", { className: "h-4 w-px bg-border-subtle" }), _jsxs("span", { className: "text-[11px] font-mono uppercase tracking-wider text-text-muted", children: ["P", phase] }), _jsx("span", { className: "hidden lg:inline text-[12px] text-text-secondary", children: PHASE_NAMES[phase] }), _jsx("div", { className: "h-4 w-px bg-border-subtle" }), _jsxs("span", { className: "text-[12px] font-mono text-text-muted", children: ["DAY ", _jsx("span", { className: "text-text-primary font-semibold", children: String(day).padStart(2, '0') })] }), _jsxs("span", { className: "text-[11px] font-mono text-text-muted/60", children: ["WK ", week] })] })] }), _jsxs("div", { className: "hidden md:flex items-center gap-1.5", children: [_jsx(KpiPill, { label: "Budget", value: `€${resources.budget}k` }), _jsx(KpiPill, { label: "Capacity", value: `${resources.teamCapacity}%`, color: resources.teamCapacity < 30 ? 'text-state-danger' : undefined }), _jsx(KpiPill, { label: "Momentum", value: resources.dealMomentum, color: resources.dealMomentum > 60 ? 'text-state-success' : undefined }), _jsx(KpiPill, { label: "Trust", value: resources.clientTrust }), _jsx(KpiPill, { label: "Risk", value: resources.riskLevel, color: resources.riskLevel > 50 ? 'text-state-danger' : resources.riskLevel > 30 ? 'text-state-warning' : 'text-state-success' })] }), _jsxs("div", { className: "flex items-center gap-1 relative", children: [_jsxs("button", { onClick: () => setShowNotifications(!showNotifications), className: "relative p-2 rounded-[var(--radius-md)] text-text-muted hover:text-text-primary hover:bg-surface-hover transition-colors duration-150", children: [_jsx(Bell, { size: 16 }), unreadCount > 0 && (_jsx("span", { className: "absolute top-1 right-1 w-2 h-2 rounded-full bg-accent-primary animate-pulse" }))] }), _jsx("button", { onClick: () => setShowSettings(true), className: "p-2 rounded-[var(--radius-md)] text-text-muted hover:text-text-primary hover:bg-surface-hover transition-colors duration-150", title: "Settings", children: _jsx(Settings, { size: 16 }) }), _jsx(NotificationsPopover, { isOpen: showNotifications, onClose: () => setShowNotifications(false) }), _jsx(SettingsModal, { isOpen: showSettings, onClose: () => setShowSettings(false) })] })] }));
}
//# sourceMappingURL=Topbar.js.map