import type { GameTask, Email, Deliverable, Risk, Headline } from '../types/game';

// ============================================
// Phase 6: Due Diligence
// Manage multiple buyer DD streams, contain emerging issues, survive the grind
// Weeks 29-34 — Operational hell meets analytical precision
// ============================================

export const phase6Tasks: GameTask[] = [
  {
    id: 'task-80', name: 'Launch Structured Q&A Tracker',
    description: 'Build a centralised tracker to log every DD question across all buyer streams. Categorise by topic (financial, legal, commercial, technical, HR), assign owners, and set SLA response targets. Without this, questions fall through the cracks and buyers lose confidence.',
    phase: 6, category: 'deliverable', status: 'recommended', cost: 2, work: 14, complexity: 'medium',
    effectSummary: 'Foundation for DD management — prevents chaos',
    linkedDeliverableId: 'del-60',
  },
  {
    id: 'task-81', name: 'Triage Incoming DD Requests',
    description: 'Each buyer submits DD request lists running 200-400 items. Prioritise by materiality and buyer importance. Flag commercially sensitive requests that need client approval before disclosure. Separate the critical from the noise.',
    phase: 6, category: 'strategic', status: 'locked', cost: 0, work: 12, complexity: 'medium',
    effectSummary: 'Prevents team drowning in low-priority requests',
    dependencies: ['task-80'],
  },
  {
    id: 'task-82', name: 'Respond to Kestrel Financial DD Pack',
    description: 'Julian Mercer at KPMG is running Kestrel\'s financial DD. Their question pack is 180 items deep — EBITDA bridge, working capital normalisation, revenue quality, customer concentration, capex vs opex classification. Every answer must be defensible. Errors here crater the bid.',
    phase: 6, category: 'deliverable', status: 'locked', cost: 0, work: 14, complexity: 'high',
    effectSummary: 'Critical — Kestrel\'s bid price depends on these answers',
    dependencies: ['task-81'],
  },
  {
    id: 'task-83', name: 'Respond to Schneider Legal DD Checklist',
    description: 'Sarah Jenkins has sent Schneider\'s legal DD checklist — 240 items covering IP ownership, employment contracts, regulatory compliance, litigation history, and data protection. Volume is crushing. Prioritise material items and flag anything that requires external counsel.',
    phase: 6, category: 'deliverable', status: 'locked', cost: 5, work: 12, complexity: 'high',
    effectSummary: 'Schneider will not bid without legal comfort',
    dependencies: ['task-81'],
  },
  {
    id: 'task-84', name: 'Respond to Vektor Commercial DD Pack',
    description: 'Vektor\'s DD is leaner but sharper — 90 targeted questions on customer churn, pipeline conversion, competitive positioning, and technology moat. They already know the sector. Weak answers here will be exploited in price negotiation.',
    phase: 6, category: 'deliverable', status: 'locked', cost: 0, work: 12, complexity: 'high',
    effectSummary: 'Vektor will retrade aggressively on any gaps found',
    dependencies: ['task-81'],
  },
  {
    id: 'task-85', name: 'Investigate EBITDA Reconciliation Issue',
    description: 'Kestrel\'s advisors have flagged a €1.2M discrepancy between the CIM EBITDA and the audited accounts. It may be an add-back classification issue, or it may be a real problem. Investigate immediately — if this isn\'t resolved, it becomes a price chip.',
    phase: 6, category: 'internal', status: 'locked', cost: 0, work: 14, complexity: 'high',
    effectSummary: 'Must resolve before it becomes a valuation haircut',
    dependencies: ['task-82'],
  },
  {
    id: 'task-86', name: 'Draft Issue Response Memo',
    description: 'Document all DD issues surfaced by buyers, with root cause analysis, mitigation narrative, and supporting evidence. This memo is the deal\'s immune system — it pre-empts buyer objections and prevents issues from metastasising into price reductions.',
    phase: 6, category: 'deliverable', status: 'locked', cost: 3, work: 12, complexity: 'high',
    effectSummary: 'Contains emerging issues before they erode value',
    dependencies: ['task-85'],
    linkedDeliverableId: 'del-61',
  },
  {
    id: 'task-87', name: 'Build Mitigation Pack',
    description: 'For each material DD finding, prepare a mitigation narrative with supporting documentation: management commentary, third-party validation, trend data, and comparable benchmarks. Buyers need reasons to look past issues, not just explanations.',
    phase: 6, category: 'strategic', status: 'locked', cost: 5, work: 12, complexity: 'high',
    effectSummary: 'Converts issues into managed risks in buyer minds',
    dependencies: ['task-86'],
  },
  {
    id: 'task-88', name: 'Refresh Data Room',
    description: 'Upload new documents requested during DD, re-index folders, fix broken links, and ensure version control. Buyers judge process quality by data room hygiene. A messy room signals a messy company.',
    phase: 6, category: 'internal', status: 'available', cost: 2, work: 10, complexity: 'medium',
    effectSummary: '+4 reputation, demonstrates process rigour',
    linkedDeliverableId: 'del-62',
  },
  {
    id: 'task-89', name: 'Prepare Management for DD Sessions',
    description: 'Coach Ricardo, Helena, and Tomás for live DD sessions with buyer advisory teams. They will be grilled on financials, operations, technology, and strategy. Unprepped management destroys buyer confidence in minutes.',
    phase: 6, category: 'relationship', status: 'locked', cost: 0, work: 12, complexity: 'high',
    effectSummary: '+8 trust, management performance is make-or-break',
    dependencies: ['task-81'],
    workstreamId: 'management',
  },
  {
    id: 'task-90', name: 'Align Client on Disclosure Strategy',
    description: 'Walk Ricardo through what must be disclosed, what can be deferred, and what is genuinely sensitive. He will resist sharing certain information. Push too hard and you lose trust; too soft and you risk post-signing claims.',
    phase: 6, category: 'relationship', status: 'locked', cost: 0, work: 8, complexity: 'medium',
    effectSummary: 'Balances transparency with client comfort',
    dependencies: ['task-89'],
  },
  {
    id: 'task-91', name: 'Retain Shaky Bidder',
    description: 'One buyer is going quiet — response times are slowing, questions are becoming superficial, and their DD team has been downsized. Re-engage with a targeted call. Losing a bidder now kills competitive tension when you need it most.',
    phase: 6, category: 'strategic', status: 'available', cost: 0, work: 6, complexity: 'low',
    effectSummary: 'Preserves competitive dynamics, +4 momentum',
  },
  {
    id: 'task-92', name: 'Final DD Readiness Review',
    description: 'Comprehensive status check across all buyer DD streams. Confirm all material questions answered, outstanding items tracked, issue memos circulated, and process letter ready for distribution. The gate to the binding bid phase.',
    phase: 6, category: 'deliverable', status: 'locked', cost: 0, work: 10, complexity: 'medium',
    effectSummary: 'Gate — confirms readiness for final bids',
    dependencies: ['task-86', 'task-88'],
    linkedDeliverableId: 'del-63',
  },
];

export const phase6Emails: Email[] = [
  {
    id: 'email-80',
    week: 29,
    phase: 6,
    sender: 'Marcus Aldridge',
    senderRole: 'Managing Partner',
    subject: 'DD is where deals die — don\'t let this one',
    body: 'Due diligence has officially started across all three buyer streams. This is the most dangerous phase of the process.\n\nEvery unanswered question is a seed of doubt. Every slow response is a signal that something is being hidden. Every inconsistency between what we said in the CIM and what DD reveals is a price chip.\n\nI want three things from you:\n1. A structured Q&A tracker — centralised, SLA-driven, no question goes unanswered for more than 48 hours\n2. A weekly DD status report on my desk every Friday\n3. Immediate escalation of any issue that could move the needle on valuation\n\nKestrel has hired KPMG and they will be thorough. Schneider\'s legal team will bury us in checklists. Vektor already knows the sector — their questions will be surgical.\n\nDon\'t drown. Triage ruthlessly.',
    preview: 'DD phase starts — triage ruthlessly, 48-hour SLA on all questions...',
    category: 'partner',
    state: 'unread',
    priority: 'high',
    timestamp: 'Week 29, Monday',
    responseOptions: [
      { id: 'r1', label: 'Tracker is being built now. I\'ll own the triage personally.', effects: '+6 momentum, +3 reputation', resourceEffects: { dealMomentum: 6, reputation: 3 } },
      { id: 'r2', label: 'Understood. I need to pull Sofia off other work to handle the volume — requesting additional analyst support.', effects: '+4 momentum, +5 teamCapacity', resourceEffects: { dealMomentum: 4, teamCapacity: 5 } },
      { id: 'r3', label: 'We should consider retaining external DD support to handle the Schneider legal stream — it\'s too large for our team alone.', effects: '+3 momentum, -8 budget', resourceEffects: { dealMomentum: 3, budget: -8 } },
    ],
  },
  {
    id: 'email-81',
    week: 29,
    phase: 6,
    sender: 'Julian Mercer',
    senderRole: 'Director, KPMG Transaction Services (Advising Kestrel Capital)',
    subject: 'Financial DD — Initial Request List',
    body: 'Dear Team,\n\nPlease find attached Kestrel Capital\'s Phase 1 financial due diligence request list (180 items). Key priority areas:\n\n- EBITDA bridge from audited accounts to management case (items 1-22)\n- Working capital normalisation methodology (items 23-41)\n- Revenue quality and customer cohort analysis (items 42-68)\n- Capex/opex classification and maintenance vs growth split (items 69-85)\n- Tax compliance and exposure review (items 86-112)\n- Employee cost analysis and key-person dependency (items 113-140)\n- Pipeline and contracted vs recurring revenue breakdown (items 141-180)\n\nWe would appreciate responses within 5 business days for priority items (flagged in red) and 10 business days for the remainder.\n\nWe will also need access to Helena Costa (CFO) for a 2-hour financial deep-dive session.\n\nRegards,\nJulian Mercer',
    preview: 'Kestrel\'s KPMG team sends 180-item financial DD request list...',
    category: 'buyer',
    state: 'unread',
    priority: 'high',
    timestamp: 'Week 29, Wednesday',
    responseOptions: [
      { id: 'r1', label: 'Acknowledge receipt and commit to 5-day turnaround on priority items. Schedule Helena session for next week.', effects: '+5 momentum, +3 reputation', resourceEffects: { dealMomentum: 5, reputation: 3 } },
      { id: 'r2', label: 'Push back on the 5-day timeline — request 8 business days given parallel buyer streams. Professional but firm.', effects: '+2 reputation, -2 momentum', resourceEffects: { reputation: 2, dealMomentum: -2 } },
      { id: 'r3', label: 'Fast-track everything — pull the whole team onto Kestrel responses. They\'re the most likely to bid aggressively.', effects: '+8 momentum, -6 morale (team overload)', resourceEffects: { dealMomentum: 8, morale: -6 } },
    ],
  },
  {
    id: 'email-82',
    week: 30,
    phase: 6,
    sender: 'Sarah Jenkins',
    senderRole: 'Partner, Clifford Chance (Advising Schneider Digital)',
    subject: 'Legal DD — Comprehensive Checklist',
    body: 'Good morning,\n\nAttached is Schneider Digital\'s legal due diligence checklist comprising 240 items across the following workstreams:\n\n- Corporate structure and governance (55 items)\n- Material contracts and change of control provisions (38 items)\n- Intellectual property portfolio and third-party licences (42 items)\n- Employment, pensions, and key-person arrangements (35 items)\n- Regulatory and compliance (28 items)\n- Litigation and disputes (22 items)\n- Data protection and GDPR compliance (20 items)\n\nPlease note that Schneider\'s internal governance requires substantially complete legal DD before their investment committee will approve a binding bid. Incomplete responses may delay or prevent bid submission.\n\nWe request a full response within 10 business days.\n\nBest regards,\nSarah Jenkins',
    preview: 'Schneider\'s Clifford Chance team sends 240-item legal DD checklist...',
    category: 'buyer',
    state: 'unread',
    priority: 'high',
    timestamp: 'Week 30, Monday',
    responseOptions: [
      { id: 'r1', label: 'Engage external legal counsel to handle the volume. We can\'t do 240 legal items in-house.', effects: '+4 momentum, -10 budget, +3 reputation', resourceEffects: { dealMomentum: 4, budget: -10, reputation: 3 } },
      { id: 'r2', label: 'Triage into three tiers: bid-critical, important, and nice-to-have. Commit to tier 1 in 7 days, rest to follow.', effects: '+5 momentum, +2 reputation', resourceEffects: { dealMomentum: 5, reputation: 2 } },
      { id: 'r3', label: 'Push back — 240 items is excessive for this stage. Request they prioritise their top 80 items.', effects: '+3 reputation, -4 momentum (Schneider may interpret as obstruction)', resourceEffects: { reputation: 3, dealMomentum: -4 } },
    ],
  },
  {
    id: 'email-83',
    week: 30,
    phase: 6,
    sender: 'Ana Ferreira',
    senderRole: 'Vice President',
    subject: 'Team capacity warning — we\'re redlining',
    body: 'I need to flag something before it becomes a crisis.\n\nWe are currently managing:\n- 180-item financial DD for Kestrel (Julian Mercer\'s team is relentless)\n- 240-item legal DD for Schneider (Sarah Jenkins wants everything yesterday)\n- 90-item commercial DD for Vektor (surgical but high-stakes)\n- Ongoing data room maintenance and uploads\n- Management session prep for Ricardo and the leadership team\n\nSofia has been working until 2am every night this week. I\'m not far behind. We are making errors — I caught two inconsistent data points in yesterday\'s Kestrel response before they went out.\n\nWe either need:\n(a) Additional analyst resource — even a secondee from another team for 3 weeks\n(b) Permission to de-prioritise one buyer stream\n(c) Client-side support — Helena\'s team could draft financial responses directly\n\nIf we keep going at this pace without relief, something important will slip through.',
    preview: 'Team at breaking point — errors emerging, requesting resource relief...',
    category: 'internal',
    state: 'unread',
    priority: 'high',
    timestamp: 'Week 30, Thursday',
    responseOptions: [
      { id: 'r1', label: 'Request a secondee from Marcus — the deal justifies the resource investment', effects: '+6 teamCapacity, +4 morale, -3 budget', resourceEffects: { teamCapacity: 6, morale: 4, budget: -3 } },
      { id: 'r2', label: 'Ask Helena\'s team to draft financial DD responses — we review and polish before sending', effects: '+4 teamCapacity, +3 morale, -2 clientTrust (burden on client)', resourceEffects: { teamCapacity: 4, morale: 3, clientTrust: -2 } },
      { id: 'r3', label: 'We push through — this is what deal teams do. Prioritise sleep over perfection on Tier 2 items.', effects: '-5 morale, +3 momentum', resourceEffects: { morale: -5, dealMomentum: 3 } },
      { id: 'r4', label: 'De-prioritise the weakest buyer stream. Focus firepower on the two most likely bidders.', effects: '+5 teamCapacity, +3 morale, -4 dealMomentum', resourceEffects: { teamCapacity: 5, morale: 3, dealMomentum: -4 } },
    ],
  },
  {
    id: 'email-84',
    week: 31,
    phase: 6,
    sender: 'Ricardo Mendes',
    senderRole: 'Founder & CEO, Solara Systems',
    subject: 'These questions are getting intrusive',
    body: 'I just reviewed the latest DD questions from Kestrel\'s team and I\'m not comfortable.\n\nThey want employee-by-employee compensation details, including my own package. They want customer-level margin data that we\'ve never disclosed externally. They want to know about a legal dispute from 2019 that was settled and has zero relevance to the business today.\n\nThis feels like they\'re looking for problems, not trying to understand the business. Are they trying to build a case to reduce the price?\n\nI don\'t want to disclose my personal compensation. And I\'m not giving them customer-level margins — our sales team would revolt if that leaked.\n\nWhere do we draw the line?',
    preview: 'Client pushing back on intrusive DD questions — disclosure dispute...',
    category: 'client',
    state: 'unread',
    priority: 'high',
    timestamp: 'Week 31, Tuesday',
    responseOptions: [
      { id: 'r1', label: 'These are standard DD requests, Ricardo. Refusing signals you have something to hide. Let me redact individual names but provide the data.', effects: '+5 reputation, -3 clientTrust', resourceEffects: { reputation: 5, clientTrust: -3 } },
      { id: 'r2', label: 'I hear you. Let me push back on the personal comp and provide anonymised customer data. We\'ll disclose the 2019 matter in summary form.', effects: '+6 clientTrust, +2 momentum', resourceEffects: { clientTrust: 6, dealMomentum: 2 } },
      { id: 'r3', label: 'You\'re right to be cautious. I\'ll negotiate a disclosure framework with Julian\'s team — what\'s essential vs what\'s a fishing expedition.', effects: '+8 clientTrust, -2 momentum', resourceEffects: { clientTrust: 8, dealMomentum: -2 } },
    ],
  },
  {
    id: 'email-85',
    week: 31,
    phase: 6,
    sender: 'Sofia Lindqvist',
    senderRole: 'Analyst',
    subject: 'Data room issue — version conflict on financial model',
    body: 'We have a problem. Two versions of the financial model are in the data room — the original CIM model (v3.2) and the updated model reflecting Q3 actuals (v4.1). Kestrel\'s team has been referencing v3.2 and some of their DD questions are based on numbers that have since been updated.\n\nWorse — Vektor\'s team appears to have downloaded v4.1, which means the two buyer streams are working off different numbers.\n\nI\'ve also noticed that three documents in the legal folder have incorrect upload dates, making them appear older than they are.\n\nI can fix all of this but it will take a full day, and Julian Mercer\'s team has a call with Helena tomorrow morning.\n\nWhat\'s the priority?',
    preview: 'Data room version conflict — buyers working off different numbers...',
    category: 'internal',
    state: 'unread',
    priority: 'high',
    timestamp: 'Week 31, Wednesday',
    responseOptions: [
      { id: 'r1', label: 'Fix the model version immediately and notify all buyers of the update. Transparency now prevents credibility damage later.', effects: '+5 reputation, +3 momentum, -2 clientTrust (looks sloppy)', resourceEffects: { reputation: 5, dealMomentum: 3, clientTrust: -2 } },
      { id: 'r2', label: 'Fix it quietly — update v3.2 to v4.1 and brief Julian\'s team before the Helena call. Don\'t broadcast the error.', effects: '+4 momentum, -3 reputation (if discovered later)', resourceEffects: { dealMomentum: 4, reputation: -3 } },
      { id: 'r3', label: 'Pause the Helena call. Fix the data room first. We cannot have a DD session referencing wrong numbers.', effects: '+4 reputation, -3 momentum', resourceEffects: { reputation: 4, dealMomentum: -3 } },
    ],
  },
  {
    id: 'email-86',
    week: 32,
    phase: 6,
    sender: 'Julian Mercer',
    senderRole: 'Director, KPMG Transaction Services (Advising Kestrel Capital)',
    subject: 'EBITDA reconciliation — discrepancy identified',
    body: 'We have identified a €1.2M discrepancy between the adjusted EBITDA presented in the CIM (€18.7M) and our reconstruction from the audited financial statements and management adjustments provided in DD.\n\nSpecifically:\n- The add-back for "non-recurring consulting costs" (€0.6M) does not appear in the audited P&L line items provided\n- The working capital normalisation includes a €0.4M adjustment that appears to double-count a receivables provision\n- A further €0.2M relates to an intercompany recharge that we cannot reconcile to the transfer pricing documentation\n\nWe require a detailed reconciliation with source documentation within 3 business days. Please note that unresolved EBITDA adjustments will be reflected in Kestrel\'s final bid pricing.\n\nRegards,\nJulian',
    preview: 'KPMG flags €1.2M EBITDA discrepancy — requires urgent reconciliation...',
    category: 'buyer',
    state: 'unread',
    priority: 'high',
    timestamp: 'Week 32, Monday',
    responseOptions: [
      { id: 'r1', label: 'Treat this as top priority. Pull Helena into an emergency session today to reconstruct the bridge line by line.', effects: '+4 momentum, +5 reputation, -3 teamCapacity', resourceEffects: { dealMomentum: 4, reputation: 5, teamCapacity: -3 } },
      { id: 'r2', label: 'Acknowledge the discrepancy professionally and request 5 business days. We need to get this right, not fast.', effects: '+3 reputation, -2 momentum', resourceEffects: { reputation: 3, dealMomentum: -2 } },
      { id: 'r3', label: 'Frame this as a classification difference, not an error. Provide the reconciliation with a narrative that protects the CIM EBITDA figure.', effects: '+5 momentum, -3 reputation (if narrative doesn\'t hold)', resourceEffects: { dealMomentum: 5, reputation: -3 } },
    ],
  },
  {
    id: 'email-87',
    week: 33,
    phase: 6,
    sender: 'Ricardo Mendes',
    senderRole: 'Founder & CEO, Solara Systems',
    subject: 'The EBITDA issue — tell me the truth',
    body: 'Helena briefed me on the EBITDA reconciliation issue that Kestrel\'s advisors raised. I need a straight answer.\n\nIs this a real problem or an accounting technicality? Because if our headline EBITDA number was wrong in the CIM, that\'s not just a DD finding — that\'s a credibility issue. Every buyer will recalculate their bid downward.\n\nI trusted the numbers you put in the CIM. Helena says she flagged the consulting add-back as borderline during preparation but was told to include it.\n\nI\'m not looking for blame. I\'m looking for containment. How bad is this and what\'s the plan?',
    preview: 'Client demands straight answer on EBITDA credibility...',
    category: 'client',
    state: 'unread',
    priority: 'high',
    timestamp: 'Week 33, Tuesday',
    responseOptions: [
      { id: 'r1', label: 'The add-backs are defensible but require better documentation. We\'re building a watertight reconciliation. The headline number holds.', effects: '+6 clientTrust, +3 momentum', resourceEffects: { clientTrust: 6, dealMomentum: 3 } },
      { id: 'r2', label: 'We should proactively adjust the number down by €0.6M and present a revised bridge. Better we control the narrative than let KPMG do it.', effects: '+5 reputation, +4 clientTrust, -4 dealMomentum', resourceEffects: { reputation: 5, clientTrust: 4, dealMomentum: -4 } },
      { id: 'r3', label: 'The issue is containable. I\'m drafting an Issue Response Memo that addresses all three line items with source documentation. Kestrel will move past this.', effects: '+4 clientTrust, +4 momentum, +2 reputation', resourceEffects: { clientTrust: 4, dealMomentum: 4, reputation: 2 } },
    ],
  },
  {
    id: 'email-88',
    week: 33,
    phase: 6,
    sender: 'Ricardo Mendes',
    senderRole: 'Founder & CEO, Solara Systems',
    subject: 'RE: DD update — feeling better about this',
    body: 'Thank you for the Issue Response Memo. It\'s thorough and I can see the team has worked incredibly hard.\n\nThe management DD session with Kestrel went well — Julian\'s team was tough but fair, and Helena handled the financial deep-dive like a pro. Tomás impressed them on the technology roadmap.\n\nI feel like we\'ve turned a corner on the EBITDA issue. The documentation you provided was convincing.\n\nOne concern: Schneider has gone quieter this week. Their questions have slowed down and Sarah Jenkins cancelled a follow-up call. Should I be worried?\n\nAlso — my team is exhausted. Helena hasn\'t had a weekend off in a month. How much longer does this phase last?',
    preview: 'Client cautiously optimistic after containment — concerned about Schneider going quiet...',
    category: 'client',
    state: 'unread',
    priority: 'normal',
    timestamp: 'Week 33, Friday',
    responseOptions: [
      { id: 'r1', label: 'Schneider\'s slowdown is normal — their governance is heavy. I\'ll reach out to Sarah Jenkins to confirm they\'re still on track. Tell Helena to take this weekend off.', effects: '+6 clientTrust, +3 morale', resourceEffects: { clientTrust: 6, morale: 3 } },
      { id: 'r2', label: 'I\'ll probe Schneider directly. If they\'re cooling, we need to know now — not after the bid deadline. Let\'s also give your team a breather this weekend.', effects: '+4 clientTrust, +4 momentum, +2 morale', resourceEffects: { clientTrust: 4, dealMomentum: 4, morale: 2 } },
      { id: 'r3', label: 'Schneider may be deprioritising. We should intensify focus on Vektor and Kestrel — they\'re the real contenders. We\'re 1-2 weeks from finishing DD.', effects: '+5 momentum, -2 clientTrust (Ricardo wants Schneider)', resourceEffects: { dealMomentum: 5, clientTrust: -2 } },
    ],
  },
  {
    id: 'email-89',
    week: 34,
    phase: 6,
    sender: 'Ana Ferreira',
    senderRole: 'Vice President',
    subject: 'DD readiness assessment — where we stand',
    body: 'Status across all three streams heading into final week:\n\n**Kestrel Capital (via KPMG / Julian Mercer)**\n- 168 of 180 financial DD items answered (93%)\n- EBITDA reconciliation resolved with supporting documentation\n- Management session completed — positive feedback\n- Outstanding: 12 items on tax and intercompany, expected by Thursday\n\n**Schneider Digital (via Clifford Chance / Sarah Jenkins)**\n- 195 of 240 legal DD items answered (81%)\n- IP and employment workstreams complete\n- Outstanding: regulatory compliance (18 items) and data protection (27 items)\n- Sarah\'s team has been slower to engage this week — may be internal governance review\n\n**Vektor Industries**\n- 85 of 90 commercial DD items answered (94%)\n- Management session scheduled for next week\n- Outstanding: 5 items on customer concentration and pipeline methodology\n\nOverall: we are in credible shape. The Q&A tracker worked — average response time was 3.2 days across all streams. The Issue Response Memo contained the EBITDA issue.\n\nRecommendation: issue the final process letter this week, inviting binding bids within 3 weeks.',
    preview: 'DD status: 93% Kestrel, 81% Schneider, 94% Vektor — ready for final bids...',
    category: 'internal',
    state: 'unread',
    priority: 'high',
    timestamp: 'Week 34, Monday',
    responseOptions: [
      { id: 'r1', label: 'Excellent work. Issue the final process letter — we\'re ready for binding bids.', effects: '+8 momentum, +5 reputation, +3 morale', resourceEffects: { dealMomentum: 8, reputation: 5, morale: 3 } },
      { id: 'r2', label: 'Close out the Schneider gaps first. I don\'t want to issue the process letter until all streams are above 90%.', effects: '+3 reputation, -3 momentum', resourceEffects: { reputation: 3, dealMomentum: -3 } },
      { id: 'r3', label: 'Issue the letter to Vektor and Kestrel now. Give Schneider an extra week — but make it clear this is the final extension.', effects: '+5 momentum, +2 reputation', resourceEffects: { dealMomentum: 5, reputation: 2 } },
    ],
  },
];

export const phase6Deliverables: Deliverable[] = [
  {
    id: 'del-60',
    name: 'Structured Q&A Tracker',
    phase: 6,
    status: 'not_started',
    completion: 0,
    quality: 'adequate',
    dependencies: ['task-80'],
  },
  {
    id: 'del-61',
    name: 'Issue Response Memo',
    phase: 6,
    status: 'not_started',
    completion: 0,
    quality: 'adequate',
    dependencies: ['task-86'],
  },
  {
    id: 'del-62',
    name: 'Data Room Refresh',
    phase: 6,
    status: 'not_started',
    completion: 0,
    quality: 'adequate',
    dependencies: ['task-88'],
  },
  {
    id: 'del-63',
    name: 'Final Process Letter',
    phase: 6,
    status: 'not_started',
    completion: 0,
    quality: 'adequate',
    dependencies: ['task-92'],
  },
];

export const phase6Risks: Risk[] = [
  {
    id: 'risk-60',
    name: 'EBITDA Reconciliation Failure',
    description: 'KPMG has flagged a €1.2M discrepancy in adjusted EBITDA. If not resolved convincingly, every buyer will haircut the valuation. The gap between CIM EBITDA and auditable EBITDA becomes the defining issue of the process.',
    category: 'diligence',
    severity: 'high',
    probability: 35,
    mitigated: false,
    surfacedWeek: 32,
    surfacedPhase: 6,
  },
  {
    id: 'risk-61',
    name: 'Buyer Attrition — Schneider Withdrawal',
    description: 'Schneider\'s DD engagement has slowed significantly. Their internal governance complexity and the sheer volume of unresolved legal items may cause their investment committee to decline bid approval. Losing Schneider removes a strategic bidder and weakens competitive tension.',
    category: 'buyer',
    severity: 'high',
    probability: 40,
    mitigated: false,
    surfacedWeek: 33,
    surfacedPhase: 6,
  },
  {
    id: 'risk-62',
    name: 'Team Burnout Under DD Load',
    description: 'The team is managing 500+ DD items across three simultaneous buyer streams. Errors are emerging due to fatigue — inconsistent data points, missed deadlines, and declining response quality. A material error in a DD response could trigger a formal finding.',
    category: 'team',
    severity: 'medium',
    probability: 45,
    mitigated: false,
    surfacedWeek: 30,
    surfacedPhase: 6,
  },
  {
    id: 'risk-63',
    name: 'Data Room Breach or Leak',
    description: 'Multiple buyer advisory teams now have deep access to commercially sensitive information. A data room version conflict has already occurred. The risk of inadvertent disclosure of customer-level data, employee compensation, or competitive intelligence increases with every new document uploaded.',
    category: 'diligence',
    severity: 'high',
    probability: 25,
    mitigated: false,
    surfacedWeek: 31,
    surfacedPhase: 6,
  },
];

export const phase6Headlines: Headline[] = [
  { id: 'hl-60', week: 29, text: 'KPMG publishes annual M&A DD survey — average deal sees 12% EBITDA adjustment during diligence.', category: 'sector' },
  { id: 'hl-61', week: 30, text: 'European data protection authority announces increased enforcement actions — DD data handling under scrutiny.', category: 'regulatory' },
  { id: 'hl-62', week: 31, text: 'Kestrel Capital closes Fund VII at €2.4B — well above target, signalling strong LP confidence.', category: 'buyer_strategy' },
  { id: 'hl-63', week: 32, text: 'Industrial automation M&A multiples compress 0.5x amid Q3 earnings misses across the sector.', category: 'comparable' },
  { id: 'hl-64', week: 33, text: 'Schneider Digital CEO signals "disciplined approach to bolt-on acquisitions" in investor call.', category: 'buyer_strategy' },
  { id: 'hl-65', week: 34, text: 'ECB holds rates steady — financing conditions stable for leveraged buyouts.', category: 'macro' },
];
