export const REVIEW_CHECKPOINTS = [
    {
        id: 'p0-kickoff',
        phase: 0,
        label: 'Kickoff',
        description: 'Origination fresca, sem board nem qual notes.',
        route: '/game',
        day: 1,
        clientTrust: 40,
        dealMomentum: 15,
        riskLevel: 10,
    },
    {
        id: 'p0-gate-ready',
        phase: 0,
        label: 'Gate Ready',
        description: 'Lead qualificado, meeting feita, board aprovado.',
        route: '/client',
        day: 18,
        clientTrust: 55,
        dealMomentum: 42,
        riskLevel: 18,
        boardApproved: true,
        leadInvestigated: true,
        leadMeetingDone: true,
        qualificationNotes: 2,
    },
    {
        id: 'p1-pitch-build',
        phase: 1,
        label: 'Pitch Build',
        description: 'A montar investment case e deck.',
        route: '/tasks',
        day: 22,
        clientTrust: 52,
        dealMomentum: 45,
        riskLevel: 20,
    },
    {
        id: 'p1-fee-agreed',
        phase: 1,
        label: 'Mandate Won',
        description: 'Pitch entregue e fee terms fechados.',
        route: '/client',
        day: 30,
        clientTrust: 68,
        dealMomentum: 58,
        riskLevel: 16,
        completedTaskIds: ['task-10', 'task-12', 'task-13', 'task-14', 'task-15', 'task-16'],
        pitchDocumentReady: true,
        feeAgreed: true,
    },
    {
        id: 'p2-materials-build',
        phase: 2,
        label: 'Materials Build',
        description: 'Modelo, CIM e teaser em construção.',
        route: '/deliverables',
        day: 40,
        clientTrust: 64,
        dealMomentum: 52,
        riskLevel: 24,
    },
    {
        id: 'p2-launch-ready',
        phase: 2,
        label: 'Launch Ready',
        description: 'Materiais core prontos para ir ao mercado.',
        route: '/deliverables',
        day: 52,
        clientTrust: 72,
        dealMomentum: 65,
        riskLevel: 20,
        completedTaskIds: ['task-20', 'task-21', 'task-22', 'task-25', 'task-24', 'task-29', 'task-30'],
    },
    {
        id: 'p3-outreach-live',
        phase: 3,
        label: 'Outreach Live',
        description: 'Teasers enviados e NDAs a entrar.',
        route: '/buyers',
        day: 58,
        clientTrust: 68,
        dealMomentum: 60,
        riskLevel: 26,
    },
    {
        id: 'p3-shortlist-ready',
        phase: 3,
        label: 'Shortlist Ready',
        description: 'Q&A respondido e deadline batido para seguir.',
        route: '/buyers',
        day: 78,
        clientTrust: 70,
        dealMomentum: 66,
        riskLevel: 24,
        completedTaskIds: ['task-40', 'task-42', 'task-43', 'task-45', 'task-46', 'task-48', 'task-49'],
        phaseDeadlineDay: 72,
        buyerStatuses: {
            'buyer-01': 'active',
            'buyer-02': 'nda_signed',
            'buyer-03': 'active',
            'buyer-04': 'reviewing',
            'buyer-05': 'active',
        },
    },
    {
        id: 'p4-shortlist-build',
        phase: 4,
        label: 'Shortlist Build',
        description: 'A limpar buyers e a definir round de NBO.',
        route: '/buyers',
        day: 82,
        clientTrust: 69,
        dealMomentum: 63,
        riskLevel: 25,
    },
    {
        id: 'p4-nbo-ready',
        phase: 4,
        label: 'NBO Ready',
        description: 'Shortlist fechada e deadline para first round.',
        route: '/timeline',
        day: 96,
        clientTrust: 72,
        dealMomentum: 68,
        riskLevel: 22,
        completedTaskIds: ['task-60', 'task-61', 'task-63', 'task-64', 'task-66', 'task-68'],
        phaseDeadlineDay: 94,
        buyerStatuses: {
            'buyer-01': 'shortlisted',
            'buyer-03': 'shortlisted',
            'buyer-04': 'shortlisted',
            'buyer-05': 'active',
            'buyer-02': 'excluded',
        },
    },
    {
        id: 'p5-nbo-analysis',
        phase: 5,
        label: 'NBO Analysis',
        description: 'Ofertas indicativas acabadas de chegar.',
        route: '/buyers',
        day: 102,
        clientTrust: 70,
        dealMomentum: 62,
        riskLevel: 28,
    },
    {
        id: 'p5-dd-entry-ready',
        phase: 5,
        label: 'DD Entry Ready',
        description: 'Matrix pronta e candidatos a DD escolhidos.',
        route: '/deliverables',
        day: 112,
        clientTrust: 74,
        dealMomentum: 71,
        riskLevel: 24,
        completedTaskIds: ['task-70', 'task-71', 'task-72', 'task-73', 'task-74', 'task-75', 'task-76', 'task-77', 'task-78'],
        buyerStatuses: {
            'buyer-01': 'bidding',
            'buyer-03': 'bidding',
            'buyer-04': 'shortlisted',
            'buyer-05': 'excluded',
            'buyer-02': 'dropped',
        },
    },
    {
        id: 'p6-dd-live',
        phase: 6,
        label: 'DD Live',
        description: 'Q&A tracker lançado e buyer DD streams abertas.',
        route: '/dataroom',
        day: 118,
        clientTrust: 68,
        dealMomentum: 58,
        riskLevel: 34,
    },
    {
        id: 'p6-binding-bid-ready',
        phase: 6,
        label: 'Binding Bid Ready',
        description: 'Issue memo contido e process letter pronta.',
        route: '/dataroom',
        day: 138,
        clientTrust: 76,
        dealMomentum: 73,
        riskLevel: 26,
        completedTaskIds: ['task-80', 'task-81', 'task-82', 'task-84', 'task-85', 'task-86', 'task-87', 'task-88', 'task-89', 'task-90', 'task-92'],
        phaseDeadlineDay: 132,
        bindingOffersReceived: 2,
        buyerStatuses: {
            'buyer-01': 'bidding',
            'buyer-03': 'bidding',
            'buyer-04': 'active',
            'buyer-05': 'dropped',
            'buyer-02': 'dropped',
        },
    },
    {
        id: 'p7-final-offers-live',
        phase: 7,
        label: 'Final Offers Live',
        description: 'As binding offers estão na mesa.',
        route: '/final-offers',
        day: 142,
        clientTrust: 72,
        dealMomentum: 69,
        riskLevel: 30,
        bindingOffersReceived: 3,
    },
    {
        id: 'p7-exclusivity-ready',
        phase: 7,
        label: 'Exclusivity Ready',
        description: 'Preferred bidder escolhido e exclusivity pack pronto.',
        route: '/final-offers',
        day: 154,
        clientTrust: 78,
        dealMomentum: 76,
        riskLevel: 24,
        completedTaskIds: ['task-90', 'task-91', 'task-92', 'task-93', 'task-94', 'task-95', 'task-96', 'task-97', 'task-98', 'task-99', 'task-100', 'task-101', 'task-102'],
        preferredBidderId: 'buyer-03',
        buyerStatuses: {
            'buyer-01': 'shortlisted',
            'buyer-03': 'preferred',
            'buyer-04': 'bidding',
            'buyer-05': 'dropped',
            'buyer-02': 'dropped',
        },
        bindingOffersReceived: 3,
    },
    {
        id: 'p8-spa-live',
        phase: 8,
        label: 'SPA Live',
        description: 'Negociação legal aberta com o bidder preferido.',
        route: '/client',
        day: 160,
        clientTrust: 74,
        dealMomentum: 67,
        riskLevel: 31,
        preferredBidderId: 'buyer-03',
        buyerStatuses: {
            'buyer-01': 'shortlisted',
            'buyer-03': 'preferred',
            'buyer-04': 'dropped',
            'buyer-05': 'dropped',
            'buyer-02': 'dropped',
        },
    },
    {
        id: 'p8-signing-ready',
        phase: 8,
        label: 'Signing Ready',
        description: 'SPA acordado e checklist de signing pronta.',
        route: '/timeline',
        day: 176,
        clientTrust: 80,
        dealMomentum: 78,
        riskLevel: 22,
        completedTaskIds: ['task-100', 'task-101', 'task-102', 'task-103', 'task-104', 'task-105', 'task-106', 'task-107', 'task-108', 'task-109', 'task-110', 'task-111'],
        preferredBidderId: 'buyer-03',
        spaAgreed: true,
        buyerStatuses: {
            'buyer-01': 'shortlisted',
            'buyer-03': 'preferred',
            'buyer-04': 'dropped',
            'buyer-05': 'dropped',
            'buyer-02': 'dropped',
        },
    },
    {
        id: 'p9-signing-desk',
        phase: 9,
        label: 'Signing Desk',
        description: 'Documentos quase prontos para assinar.',
        route: '/timeline',
        day: 182,
        clientTrust: 77,
        dealMomentum: 72,
        riskLevel: 26,
        preferredBidderId: 'buyer-03',
    },
    {
        id: 'p9-closing-ready',
        phase: 9,
        label: 'Closing Ready',
        description: 'Signature version locked e SPA assinada.',
        route: '/timeline',
        day: 194,
        clientTrust: 84,
        dealMomentum: 80,
        riskLevel: 18,
        completedTaskIds: ['task-110', 'task-111', 'task-112', 'task-113', 'task-114', 'task-115', 'task-116', 'task-117', 'task-118', 'task-119'],
        preferredBidderId: 'buyer-03',
        spaAgreed: true,
    },
    {
        id: 'p10-closing-live',
        phase: 10,
        label: 'Closing Live',
        description: 'CP tracker, wires e pressão final.',
        route: '/game',
        day: 200,
        clientTrust: 82,
        dealMomentum: 76,
        riskLevel: 25,
        preferredBidderId: 'buyer-03',
    },
    {
        id: 'p10-results-ready',
        phase: 10,
        label: 'Results Ready',
        description: 'Mais de 70% da fase completa, quase no scoring final.',
        route: '/game',
        day: 214,
        clientTrust: 88,
        dealMomentum: 85,
        riskLevel: 16,
        completedTaskIds: ['task-120', 'task-121', 'task-122', 'task-123', 'task-124', 'task-125', 'task-126', 'task-128', 'task-129', 'task-130'],
        preferredBidderId: 'buyer-03',
    },
];
export const REVIEW_CHECKPOINTS_BY_ID = Object.fromEntries(REVIEW_CHECKPOINTS.map((checkpoint) => [checkpoint.id, checkpoint]));
//# sourceMappingURL=reviewCheckpoints.js.map