// ============================================
// Phase 8: SPA Negotiation
// Clause-by-clause legal marathon to signature
// Weeks 39-43 — Protect value while reaching the finish line
// ============================================
export const phase8Tasks = [
    {
        id: 'task-100', name: 'Build Clause Priority Map',
        description: 'Map every SPA clause into three tiers: non-negotiable (fundamental warranties, cap structure), tradeable (operational reps, disclosure timing), and concedable (minor scheduling, notice periods). Without this framework every clause becomes a war.',
        phase: 8, category: 'deliverable', status: 'recommended', cost: 2, work: 14, complexity: 'high',
        effectSummary: 'Creates negotiation framework — prevents value leakage',
        linkedDeliverableId: 'del-80',
    },
    {
        id: 'task-101', name: 'Package Linked Issues',
        description: 'Group interdependent clauses into negotiation packages so concessions in one area unlock value in another. Indemnity cap linked to escrow size linked to warranty duration — force Kestrel to evaluate trade-offs holistically.',
        phase: 8, category: 'strategic', status: 'locked', cost: 0, work: 10, complexity: 'high',
        effectSummary: '+6 momentum, prevents cherry-picking by buyer counsel',
        dependencies: ['task-100'],
    },
    {
        id: 'task-102', name: 'Push Back Aggressive Markup',
        description: 'Sarah Jenkins has returned the SPA with over 140 markups. Systematically reject overreach on liability caps, broad indemnity language, and open-ended warranty claims. Set the tone: this is a negotiation, not a capitulation.',
        phase: 8, category: 'strategic', status: 'locked', cost: 3, work: 14, complexity: 'high',
        effectSummary: 'Defends value, signals strength — risk of stalling if overdone',
        dependencies: ['task-100'],
    },
    {
        id: 'task-103', name: 'Hold Line on High-Value Protections',
        description: 'Certain clauses are existential for Ricardo: the indemnity cap must stay at a reasonable percentage of enterprise value, fundamental warranties must have clean carve-outs, and the escrow holdback cannot exceed 10%. These are the hills to die on.',
        phase: 8, category: 'strategic', status: 'locked', cost: 0, work: 12, complexity: 'high',
        effectSummary: 'Protects core deal economics — critical for client trust',
        dependencies: ['task-102'],
    },
    {
        id: 'task-104', name: 'Accept Controlled Compromises',
        description: 'Identify two or three clauses where yielding costs the seller little but feels like a win for Kestrel\'s counsel. Extended non-compete geography, broader MAC language with carve-outs, slightly longer warranty survival. Give ground where it doesn\'t bleed.',
        phase: 8, category: 'strategic', status: 'locked', cost: 0, work: 8, complexity: 'medium',
        effectSummary: '+4 momentum, creates reciprocity for hard asks',
        dependencies: ['task-101'],
    },
    {
        id: 'task-105', name: 'Trade Concession for Certainty',
        description: 'Offer Kestrel a modest increase in the escrow holdback (from 7% to 8.5%) in exchange for a locked signing date with no further re-trade. Convert a small economic concession into binding timeline certainty.',
        phase: 8, category: 'strategic', status: 'locked', cost: 0, work: 6, complexity: 'medium',
        effectSummary: '+8 momentum, locks timeline — small economic cost',
        dependencies: ['task-103', 'task-104'],
    },
    {
        id: 'task-106', name: 'Brief Client on Trade-Offs',
        description: 'Walk Ricardo through every concession, what it costs in real terms, and what it buys in deal certainty. He will resist the inventory warranty language and the escrow increase. Frame it as the price of getting signed.',
        phase: 8, category: 'relationship', status: 'locked', cost: 0, work: 10, complexity: 'high',
        effectSummary: 'Gate — client must accept SPA package to proceed',
        dependencies: ['task-105'],
    },
    {
        id: 'task-107', name: 'Test Preferred Bidder Stability',
        description: 'Probe Kestrel\'s investment committee conviction through back-channel conversations with their deal partner. Are they still fully committed, or is the legal grind creating internal fatigue? Early warning of wobble is worth everything.',
        phase: 8, category: 'market', status: 'available', cost: 0, work: 6, complexity: 'medium',
        effectSummary: 'Early warning on buyer instability — intelligence gathering',
    },
    {
        id: 'task-108', name: 'Tighten Fallback Signalling',
        description: 'Discreetly signal to Vektor that the process has not yet concluded. Don\'t reveal specifics, but keep the backup bidder warm enough to serve as leverage without triggering exclusivity breach concerns.',
        phase: 8, category: 'strategic', status: 'available', cost: 0, work: 5, complexity: 'medium',
        effectSummary: '+4 momentum, preserves backup leverage — must be subtle',
    },
    {
        id: 'task-109', name: 'Build Signing Checklist',
        description: 'Compile the full conditions precedent for signing: board resolutions, regulatory clearances, escrow account setup, disclosure schedules finalised, side letters executed. Every unresolved item is a reason to delay.',
        phase: 8, category: 'deliverable', status: 'locked', cost: 1, work: 12, complexity: 'medium',
        effectSummary: 'Prevents last-minute surprises at signing table',
        dependencies: ['task-105'],
        linkedDeliverableId: 'del-82',
    },
    {
        id: 'task-110', name: 'Run Pre-Signing Paper Review',
        description: 'Full read-through of the near-final SPA with external counsel. Check for internal inconsistencies, undefined terms, missing cross-references, and any clause that could be weaponised post-closing. Last line of defence.',
        phase: 8, category: 'external_advisor', status: 'locked', cost: 6, work: 12, complexity: 'high',
        effectSummary: 'Catches residual legal risk — expensive but essential',
        dependencies: ['task-106'],
        linkedDeliverableId: 'del-81',
    },
    {
        id: 'task-111', name: 'Reduce Residual Legal Drag',
        description: 'Resolve the remaining open items on the disclosure schedules and side letters. Each unresolved point is friction that could delay signing or give Kestrel a reason to re-open settled terms.',
        phase: 8, category: 'internal', status: 'locked', cost: 2, work: 10, complexity: 'medium',
        effectSummary: 'Clears path to signing — removes excuses for delay',
        dependencies: ['task-109'],
    },
];
export const phase8Emails = [
    {
        id: 'email-100',
        week: 39,
        phase: 8,
        sender: 'Marcus Aldridge',
        senderRole: 'Managing Partner',
        subject: 'Signing timeline — I need a date',
        body: 'We are deep in legal. I understand that. But the partnership needs a signing date it can plan around.\n\nKestrel\'s exclusivity window runs to Week 44. If we haven\'t signed by then, we are in no-man\'s-land — no exclusivity, no backup bidder warmed up, and a client who has been living in uncertainty for ten months.\n\nI need two things from you:\n1. A realistic signing date you can commit to.\n2. A clear list of what\'s blocking us from getting there.\n\nDon\'t tell me "it depends on Kestrel\'s counsel." Everything depends on their counsel. That\'s not a plan, it\'s a hope.',
        preview: 'Marcus demands a firm signing date and a blocker list...',
        category: 'partner',
        state: 'unread',
        priority: 'high',
        timestamp: 'Week 39, Monday',
        responseOptions: [
            { id: 'r1', label: 'Target Week 42 for signing. Three open issues remain — I\'ll have them closed by Week 41.', effects: '+5 momentum, +3 reputation', resourceEffects: { dealMomentum: 5, reputation: 3 } },
            { id: 'r2', label: 'Week 43 is realistic. Pushing faster risks conceding value to meet an artificial deadline.', effects: '+3 reputation, -2 momentum', resourceEffects: { reputation: 3, dealMomentum: -2 } },
            { id: 'r3', label: 'I\'ll have the blocker list today and a date by Wednesday once I\'ve tested Kestrel\'s position.', effects: '+2 momentum, +2 reputation', resourceEffects: { dealMomentum: 2, reputation: 2 } },
        ],
    },
    {
        id: 'email-101',
        week: 39,
        phase: 8,
        sender: 'Sarah Jenkins',
        senderRole: 'Counsel, Kestrel Capital',
        subject: 'SPA markup — liability and indemnity provisions',
        body: 'Please find attached our markup of the draft SPA. We have approximately 140 comments across the document. I want to flag the key commercial points for your immediate attention:\n\n1. **Indemnity cap**: We require the general indemnity cap at 50% of enterprise value. Your draft at 15% is inadequate for a business of this profile.\n2. **Warranty survival**: 36 months minimum on all operational warranties, 72 months on fundamental warranties.\n3. **Escrow**: 12% holdback for 24 months. Your proposed 7% for 18 months does not reflect the risk profile identified in due diligence.\n4. **MAC clause**: We need full market MAC protection without carve-outs for general economic conditions.\n\nThese are not starting positions. My client\'s investment committee has been clear on their risk framework.\n\nI would suggest we schedule a principals call to avoid wasting time on written exchanges.',
        preview: 'Kestrel counsel returns aggressive SPA markup — 140 comments, hard line on indemnity...',
        category: 'buyer',
        state: 'unread',
        priority: 'urgent',
        timestamp: 'Week 39, Wednesday',
        responseOptions: [
            { id: 'r1', label: 'Reject the headline positions in writing — 50% indemnity cap is a non-starter. Propose a call for Thursday.', effects: '+5 reputation, -3 momentum (confrontation risk)', resourceEffects: { reputation: 5, dealMomentum: -3 } },
            { id: 'r2', label: 'Acknowledge receipt and schedule a call for next week — give us time to build the clause priority map first.', effects: '+3 momentum, +2 reputation', resourceEffects: { dealMomentum: 3, reputation: 2 } },
            { id: 'r3', label: 'Respond selectively — concede on warranty survival length, hold firm on indemnity and escrow.', effects: '+5 momentum, -3 clientTrust (conceding without briefing client)', resourceEffects: { dealMomentum: 5, clientTrust: -3 } },
        ],
    },
    {
        id: 'email-102',
        week: 40,
        phase: 8,
        sender: 'Ana Ferreira',
        senderRole: 'Vice President',
        subject: 'False closure warning — we are not as close as it looks',
        body: 'I know the mood is that we\'re nearly there. We\'re not.\n\nI\'ve been through Kestrel\'s markup line by line. Here\'s what concerns me:\n\n- The indemnity cap gap is enormous. They\'re at 50%, we\'re at 15%. That\'s not a negotiation range, it\'s a chasm.\n- Sarah Jenkins does not move. I\'ve seen her on three other deals. She treats her markup as a final position and waits for the other side to close the gap.\n- The disclosure schedules are 40% incomplete. Every gap is a warranty risk that Kestrel will use as leverage.\n- We still don\'t have board resolution language agreed.\n\nIf we tell Marcus we\'re signing in Week 42, we are setting ourselves up for a missed deadline that damages credibility. I\'d rather give an honest Week 43 and beat it.\n\nAlso — I think we need to quietly check whether Vektor is still viable as a fallback. Our leverage with Kestrel depends on them believing we have options.',
        preview: 'Ana warns against false closure — markup gaps larger than they appear...',
        category: 'internal',
        state: 'unread',
        priority: 'high',
        timestamp: 'Week 40, Monday',
        responseOptions: [
            { id: 'r1', label: 'You\'re right. Revise the timeline to Week 43 and prioritise the disclosure schedules.', effects: '+4 reputation, -3 momentum', resourceEffects: { reputation: 4, dealMomentum: -3 } },
            { id: 'r2', label: 'I hear you, but we hold the Week 42 target. Pressure creates progress. Focus the team on the indemnity gap.', effects: '+4 momentum, -2 morale', resourceEffects: { dealMomentum: 4, morale: -2 } },
            { id: 'r3', label: 'Agreed on all points. Warm up Vektor quietly and give me a gap analysis on the disclosure schedules by Wednesday.', effects: '+3 reputation, +3 momentum, -2 budget (extra work)', resourceEffects: { reputation: 3, dealMomentum: 3, budget: -2 } },
        ],
    },
    {
        id: 'email-103',
        week: 40,
        phase: 8,
        sender: 'Ricardo Mendes',
        senderRole: 'Founder & CEO, Solara Systems',
        subject: 'Why am I guaranteeing inventory accuracy?',
        body: 'I just read the warranty section your lawyers sent over for my review.\n\nClause 7.4(b) says I am personally warranting the accuracy of Solara\'s inventory records as of closing. Personally. Me.\n\nI built this company over fifteen years. I am not a warehouse manager. I have a team that handles inventory. Are you telling me that if a pallet count is wrong somewhere in the Leipzig facility, Kestrel can come after ME for the shortfall?\n\nThis is exactly the kind of legal nonsense that makes me want to walk away from the whole process. I trusted you to protect me, and now I\'m being asked to guarantee things I cannot personally verify.\n\nExplain this to me in plain language. And tell me what you\'re doing to fix it.',
        preview: 'Ricardo furious about personal inventory warranty — threatening to walk...',
        category: 'client',
        state: 'unread',
        priority: 'urgent',
        timestamp: 'Week 40, Thursday',
        responseOptions: [
            { id: 'r1', label: 'The warranty is standard but the scope is too broad. I\'m already pushing to limit it to knowledge-qualified, company-level reps. You won\'t be personally liable.', effects: '+8 trust, +2 momentum', resourceEffects: { clientTrust: 8, dealMomentum: 2 } },
            { id: 'r2', label: 'You\'re right to flag it. I\'ll have it restructured to a company warranty with a materiality threshold by Friday.', effects: '+6 trust, +3 momentum', resourceEffects: { clientTrust: 6, dealMomentum: 3 } },
            { id: 'r3', label: 'Ricardo, these are boilerplate provisions. Every seller signs them. The indemnity cap limits your actual exposure.', effects: '-5 trust, +2 momentum (dismissive)', resourceEffects: { clientTrust: -5, dealMomentum: 2 } },
        ],
    },
    {
        id: 'email-104',
        week: 41,
        phase: 8,
        sender: 'Ricardo Mendes',
        senderRole: 'Founder & CEO, Solara Systems',
        subject: 'Can we just sign this thing?',
        body: 'I am exhausted. My CFO is exhausted. My lawyers are running up bills I didn\'t budget for.\n\nEvery week there is a new issue. Every time I think we\'re done, someone finds another clause to argue about. I have been living with this deal hanging over me for almost a year and I need it to be over.\n\nI know there are still open points. I know the indemnity cap isn\'t where you want it. But is it possible that we\'re over-optimising? That the difference between signing this week at 95% of what we want versus signing in three weeks at 98% isn\'t worth the agony?\n\nI\'m asking you honestly: is it time to compromise and sign?',
        preview: 'Ricardo exhausted — questioning whether to accept current terms and sign...',
        category: 'client',
        state: 'unread',
        priority: 'high',
        timestamp: 'Week 41, Tuesday',
        responseOptions: [
            { id: 'r1', label: 'I understand the fatigue. But the open points represent real money — another week of negotiation could save you seven figures. Trust the process.', effects: '+5 trust, +4 reputation, -3 momentum', resourceEffects: { clientTrust: 5, reputation: 4, dealMomentum: -3 } },
            { id: 'r2', label: 'You\'re closer than you think. Give me five more days. If the indemnity cap isn\'t at 20% by Friday, we sign at current terms.', effects: '+6 trust, +5 momentum', resourceEffects: { clientTrust: 6, dealMomentum: 5 } },
            { id: 'r3', label: 'If you\'re ready to accept the current package, I can have signing papers prepared by end of week. Your call.', effects: '+3 trust, +8 momentum, -5 reputation (premature)', resourceEffects: { clientTrust: 3, dealMomentum: 8, reputation: -5 } },
        ],
    },
    {
        id: 'email-105',
        week: 42,
        phase: 8,
        sender: 'James Whitfield',
        senderRole: 'Partner, Kestrel Capital',
        subject: 'Kestrel formal position on remaining open items',
        body: 'I wanted to write to you directly to set out where we are.\n\nKestrel remains fully committed to completing this acquisition. Our investment committee reaffirmed approval last Thursday. We are not going anywhere.\n\nThat said, Sarah\'s positions on the indemnity provisions reflect our fund\'s LP requirements. We have limited flexibility on the overall cap structure, though I have asked her to consider creative solutions on the escrow mechanics.\n\nSpecifically, we can offer:\n- Indemnity cap at 25% (down from 50%) if fundamental warranties are ring-fenced separately\n- Escrow at 9% for 18 months (compromise from our 12%/24 position)\n- Accelerated disclosure schedule review — we will turn comments in 48 hours\n\nIn return, we need the seller to accept 36-month survival on operational warranties and the expanded MAC language.\n\nI believe this gets us to a signable document. Can we schedule a principals call for Thursday?',
        preview: 'Kestrel partner makes formal compromise offer — indemnity at 25%, escrow at 9%...',
        category: 'buyer',
        state: 'unread',
        priority: 'high',
        timestamp: 'Week 42, Monday',
        responseOptions: [
            { id: 'r1', label: 'Constructive proposal. Counter at 20% cap and 8.5% escrow — meet in the middle. Principals call Thursday works.', effects: '+6 momentum, +3 reputation', resourceEffects: { dealMomentum: 6, reputation: 3 } },
            { id: 'r2', label: 'Accept the escrow and disclosure terms. Push back only on the indemnity cap — 22% is our floor.', effects: '+8 momentum, +2 trust', resourceEffects: { dealMomentum: 8, clientTrust: 2 } },
            { id: 'r3', label: 'Appreciate the movement. Before we respond, I need to brief my client on the warranty survival extension. Call on Friday instead.', effects: '+4 trust, +2 reputation, -2 momentum', resourceEffects: { clientTrust: 4, reputation: 2, dealMomentum: -2 } },
        ],
    },
    {
        id: 'email-106',
        week: 42,
        phase: 8,
        sender: 'Ana Ferreira',
        senderRole: 'Vice President',
        subject: 'Vektor backup leverage — window closing',
        body: 'Quick update on the fallback situation.\n\nI had a discreet conversation with Vektor\'s Corp Dev team. They remain interested in Solara but have started looking at an alternative target in the Nordic automation space. Their words: "We assumed this process was concluded. If it isn\'t, we\'d want to understand the timeline."\n\nTranslation: they\'re still reachable but cooling fast. If we want to use Vektor as genuine leverage with Kestrel, we have maybe two weeks before that card expires.\n\nThe question is whether Kestrel\'s latest proposal is good enough to sign without needing the backup, or whether we use Vektor\'s lingering interest to squeeze out a final concession.\n\nOnce Vektor commits to the Nordic target, our leverage evaporates completely.',
        preview: 'Vektor backup leverage fading — two-week window before it disappears...',
        category: 'internal',
        state: 'unread',
        priority: 'high',
        timestamp: 'Week 42, Wednesday',
        responseOptions: [
            { id: 'r1', label: 'Use it now. Signal to Kestrel that we have an alternative — force the final concession on indemnity cap.', effects: '+6 momentum, +3 dealMomentum, -4 reputation (risky bluff)', resourceEffects: { dealMomentum: 6, reputation: -4 } },
            { id: 'r2', label: 'Kestrel\'s proposal is workable. Don\'t risk the deal by overplaying our hand. Let Vektor go.', effects: '+4 reputation, +3 trust, -3 momentum', resourceEffects: { reputation: 4, clientTrust: 3, dealMomentum: -3 } },
            { id: 'r3', label: 'Keep Vektor warm for one more week as insurance, but don\'t deploy them as leverage yet. Wait for the principals call outcome.', effects: '+2 momentum, +2 reputation', resourceEffects: { dealMomentum: 2, reputation: 2 } },
        ],
    },
    {
        id: 'email-107',
        week: 43,
        phase: 8,
        sender: 'Sarah Jenkins',
        senderRole: 'Counsel, Kestrel Capital',
        subject: 'RE: Revised SPA — final comments',
        body: 'We have reviewed the revised draft incorporating the principals call outcomes.\n\nI can confirm Kestrel accepts the following:\n- General indemnity cap at 22% of enterprise value\n- Escrow holdback at 8.5% for 18 months\n- Knowledge-qualified inventory warranty at company level\n- Accelerated disclosure schedule turnaround\n\nOur remaining requirement is 36-month survival on operational warranties with the expanded MAC definition (including sector-specific downturns). This is non-negotiable.\n\nIf the seller can confirm acceptance of these final terms, I can have execution-ready documents circulated by end of week.\n\nI trust this brings the matter to conclusion.',
        preview: 'Kestrel counsel confirms near-final terms — one remaining ask on warranty survival...',
        category: 'buyer',
        state: 'unread',
        priority: 'urgent',
        timestamp: 'Week 43, Tuesday',
        responseOptions: [
            { id: 'r1', label: 'Accept the 36-month survival. Instruct external counsel to prepare execution documents. We\'re signing this week.', effects: '+10 momentum, +5 trust, +3 reputation', resourceEffects: { dealMomentum: 10, clientTrust: 5, reputation: 3 } },
            { id: 'r2', label: 'Accept survival but counter on the MAC — carve out force majeure and pandemic events. Final ask.', effects: '+5 momentum, +4 reputation, -2 trust (one more delay)', resourceEffects: { dealMomentum: 5, reputation: 4, clientTrust: -2 } },
            { id: 'r3', label: 'Need 48 hours to get client sign-off on the MAC language. Will confirm by Thursday.', effects: '+3 trust, +2 momentum', resourceEffects: { clientTrust: 3, dealMomentum: 2 } },
        ],
    },
];
export const phase8Deliverables = [
    {
        id: 'del-80',
        name: 'Clause Priority Map',
        phase: 8,
        status: 'not_started',
        completion: 0,
        quality: 'adequate',
        dependencies: ['task-100'],
    },
    {
        id: 'del-81',
        name: 'Signed SPA',
        phase: 8,
        status: 'not_started',
        completion: 0,
        quality: 'adequate',
        dependencies: ['task-110'],
    },
    {
        id: 'del-82',
        name: 'Signing Checklist',
        phase: 8,
        status: 'not_started',
        completion: 0,
        quality: 'adequate',
        dependencies: ['task-109'],
    },
];
export const phase8Risks = [
    {
        id: 'risk-80',
        name: 'Value Leakage Through Concessions',
        description: 'Cumulative small concessions on indemnity caps, escrow terms, and warranty scope can erode millions in deal value. Each clause feels minor in isolation; together they fundamentally shift the risk allocation to the seller.',
        category: 'legal',
        severity: 'high',
        probability: 40,
        mitigated: false,
        surfacedWeek: 39,
        surfacedPhase: 8,
    },
    {
        id: 'risk-81',
        name: 'Preferred Bidder Instability',
        description: 'Extended legal negotiations create internal fatigue at Kestrel. Investment committee enthusiasm decays with each week of delay, and competing deal opportunities may divert their attention and capital allocation.',
        category: 'buyer',
        severity: 'critical',
        probability: 30,
        mitigated: false,
        surfacedWeek: 40,
        surfacedPhase: 8,
    },
    {
        id: 'risk-82',
        name: 'False Closure Risk',
        description: 'Premature confidence that the deal is "almost done" leads to relaxed vigilance on disclosure schedules, side letters, and conditions precedent. Undiscovered gaps surface at the signing table, causing last-minute delays or re-trades.',
        category: 'timing',
        severity: 'high',
        probability: 40,
        mitigated: false,
        surfacedWeek: 40,
        surfacedPhase: 8,
    },
];
export const phase8Headlines = [
    { id: 'hl-80', week: 39, text: 'PE firms report record legal costs as SPA negotiations lengthen across European mid-market.', category: 'sector' },
    { id: 'hl-81', week: 40, text: 'Industrial automation M&A: average time from LOI to signing hits 14 weeks — up 30% year-on-year.', category: 'comparable' },
    { id: 'hl-82', week: 41, text: 'Kestrel Capital closes Fund IV at hard cap — dry powder signals continued acquisition appetite.', category: 'buyer_strategy' },
    { id: 'hl-83', week: 42, text: 'Nordic automation consolidation accelerates as Vektor Industries evaluates multiple targets.', category: 'competitor' },
    { id: 'hl-84', week: 43, text: 'ECB holds rates steady — financing conditions remain supportive for leveraged buyouts.', category: 'macro' },
];
//# sourceMappingURL=phase8.js.map