import type { GameTask, Email, Deliverable, Risk, Headline } from '../types/game';

// ============================================
// Phase 9: Signing
// Last-mile precision — get ink on paper
// Weeks 44-46 — The final countdown
// ============================================

export const phase9Tasks: GameTask[] = [
  {
    id: 'task-110', name: 'Run Signability Review',
    description: 'Conduct a full signability audit across all transaction documents. Check that every negotiated term has been correctly reflected, all schedules are populated, and no placeholder language remains. One overlooked bracket could delay signing by days.',
    phase: 9, category: 'deliverable', status: 'recommended', cost: 2, work: 14, complexity: 'high',
    effectSummary: 'Catches document errors before they become crises',
    linkedDeliverableId: 'del-90',
  },
  {
    id: 'task-111', name: 'Confirm Critical Issue Closure',
    description: 'Verify that every open issue flagged during SPA negotiation has been formally resolved and reflected in the final document. Cross-reference the issues log against the current markup. No loose threads.',
    phase: 9, category: 'strategic', status: 'recommended', cost: 0, work: 10, complexity: 'medium',
    effectSummary: 'Ensures no unresolved points resurface at signing',
    dependencies: ['task-110'],
  },
  {
    id: 'task-112', name: 'Finalise Document Version',
    description: 'Lock down the definitive version of the SPA and all ancillary documents. Reconcile any discrepancies between seller counsel, buyer counsel, and internal tracked versions. Version control is life or death here.',
    phase: 9, category: 'deliverable', status: 'locked', cost: 1, work: 12, complexity: 'high',
    effectSummary: 'Produces the single authoritative document set',
    dependencies: ['task-111'],
    linkedDeliverableId: 'del-90',
  },
  {
    id: 'task-113', name: 'Reconcile Markup Mismatch',
    description: 'Buyer counsel and seller counsel are working from different tracked-change bases. Identify every divergence, confirm which version reflects the agreed commercial position, and produce a single clean reconciliation. Tedious but non-negotiable.',
    phase: 9, category: 'internal', status: 'available', cost: 0, work: 8, complexity: 'medium',
    effectSummary: 'Eliminates version confusion, prevents last-minute disputes',
  },
  {
    id: 'task-114', name: 'Lock Signature Version',
    description: 'Generate the final execution version — clean, undated, with signature blocks. Circulate to all parties for confirmation that this is the document they will sign. No further changes after this point.',
    phase: 9, category: 'deliverable', status: 'locked', cost: 1, work: 6, complexity: 'medium',
    effectSummary: 'Creates the definitive signing copy',
    dependencies: ['task-112', 'task-113'],
    linkedDeliverableId: 'del-90',
  },
  {
    id: 'task-115', name: 'Brief Client Before Signing',
    description: 'Walk Ricardo through the final terms one last time. Confirm he understands the price, the conditions, the post-closing obligations, and the timeline. This is his last moment to raise concerns before the ink is irreversible.',
    phase: 9, category: 'relationship', status: 'locked', cost: 0, work: 8, complexity: 'high',
    effectSummary: 'Gate — client must give final verbal go-ahead',
    dependencies: ['task-114'],
  },
  {
    id: 'task-116', name: 'Push Counterparty for Confirmation',
    description: 'Press Kestrel to formally confirm they are ready to sign on the agreed date. Get written confirmation from their fund counsel, investment committee, and operating partner. No ambiguity.',
    phase: 9, category: 'market', status: 'locked', cost: 0, work: 6, complexity: 'medium',
    effectSummary: 'Locks buyer commitment, prevents last-minute delays',
    dependencies: ['task-114'],
  },
  {
    id: 'task-117', name: 'Identify Post-Signing Dependencies',
    description: 'Map all conditions precedent that must be satisfied between signing and closing. Regulatory approvals, third-party consents, employee notifications, landlord waivers. Build a tracker with owners and deadlines.',
    phase: 9, category: 'strategic', status: 'available', cost: 0, work: 10, complexity: 'medium',
    effectSummary: 'Prepares closing workstream, reduces post-signing chaos',
    linkedDeliverableId: 'del-91',
  },
  {
    id: 'task-118', name: 'Map Residual Obligations',
    description: 'Document all post-signing seller obligations: transition services, non-compete mechanics, escrow release conditions, earn-out cooperation requirements. Ricardo needs to understand exactly what he is committing to after the cheque clears.',
    phase: 9, category: 'internal', status: 'locked', cost: 0, work: 8, complexity: 'medium',
    effectSummary: 'Clarifies post-deal commitments for client',
    dependencies: ['task-117'],
    linkedDeliverableId: 'del-91',
  },
  {
    id: 'task-119', name: 'Trigger Signing Ceremony',
    description: 'Coordinate the simultaneous execution of all transaction documents. Manage the signing sequence: seller signs, buyer signs, escrow funded, conditions confirmed. One misstep in the choreography and the whole thing unravels.',
    phase: 9, category: 'strategic', status: 'locked', cost: 3, work: 10, complexity: 'high',
    effectSummary: 'Executes the deal — the culmination of the entire process',
    dependencies: ['task-115', 'task-116'],
  },
];

export const phase9Emails: Email[] = [
  {
    id: 'email-110',
    week: 44,
    phase: 9,
    sender: 'Marcus Aldridge',
    senderRole: 'Managing Partner',
    subject: 'Get this signed this week',
    body: 'We are on the one-yard line. Kestrel is confirmed, the SPA is agreed in substance, and Ricardo is aligned.\n\nI want ink on paper by Friday. No extensions. No "just one more round of comments." Every day we delay is a day something can go wrong — buyer remorse, a market shock, a board member getting cold feet.\n\nRun the signability check today. If there are open items, close them by Wednesday. If there is a version mismatch, fix it tonight.\n\nThis deal closes on our timeline, not theirs.',
    preview: 'Get it signed by Friday — no delays, no excuses...',
    category: 'partner',
    state: 'unread',
    priority: 'urgent',
    timestamp: 'Week 44, Monday',
    responseOptions: [
      { id: 'r1', label: 'Signability review is underway. We will be ready by Thursday for a Friday signing.', effects: '+6 momentum, +3 reputation', resourceEffects: { dealMomentum: 6, reputation: 3 } },
      { id: 'r2', label: 'There are two open items that need buyer confirmation — I can push but Friday is aggressive', effects: '+3 momentum, -2 morale (pressure)', resourceEffects: { dealMomentum: 3, morale: -2 } },
      { id: 'r3', label: 'Understood. Mobilising the full team — we will work through the night if needed.', effects: '+5 momentum, -4 morale, +2 reputation', resourceEffects: { dealMomentum: 5, morale: -4, reputation: 2 } },
    ],
  },
  {
    id: 'email-111',
    week: 44,
    phase: 9,
    sender: 'Jenny Li',
    senderRole: 'Paralegal, Kestrel Capital',
    subject: 'Document coordination — version alignment',
    body: 'Hi,\n\nI am coordinating the signing logistics on the Kestrel side. A few items:\n\n1. We have SPA v14.3 as our latest clean version. Can you confirm this matches your records?\n2. The disclosure letter references need to be cross-checked against the final schedules — our counsel flagged two mismatches in Schedule 4 (IP warranties) and Schedule 7 (employee matters).\n3. We need the signed board resolutions from Solara by close of business Wednesday.\n4. Signing sequence: we propose seller executes first, buyer countersigns within 2 hours, escrow release instruction follows immediately.\n\nPlease confirm or propose alternatives. We are aiming for a smooth process.',
    preview: 'Kestrel paralegal coordinating signing logistics — version check needed...',
    category: 'buyer',
    state: 'unread',
    priority: 'high',
    timestamp: 'Week 44, Tuesday',
    responseOptions: [
      { id: 'r1', label: 'Confirming v14.3. Will resolve schedule mismatches today and send board resolutions tomorrow.', effects: '+5 momentum, +3 reputation', resourceEffects: { dealMomentum: 5, reputation: 3 } },
      { id: 'r2', label: 'We have v14.4 as latest — let me reconcile and send you a comparison.', effects: '+2 momentum, -1 budget (extra legal hours)', resourceEffects: { dealMomentum: 2, budget: -1 } },
      { id: 'r3', label: 'Ana is on point for document coordination — looping her in to handle directly.', effects: '+2 teamCapacity, +2 momentum', resourceEffects: { teamCapacity: 2, dealMomentum: 2 } },
    ],
  },
  {
    id: 'email-112',
    week: 44,
    phase: 9,
    sender: 'Ana Ferreira',
    senderRole: 'Vice President',
    subject: 'WARNING — version control issue',
    body: 'We have a problem. I just compared our internal master against what Kestrel\'s counsel circulated yesterday and there are SEVEN differences. Most are minor formatting, but two are substantive:\n\n1. The indemnity cap in clause 12.4 — our version says €8.5M, theirs says €9.2M. This was negotiated down in the last round but someone on their side didn\'t propagate the change.\n2. The non-compete radius in Schedule 9 — we have "European Economic Area", they have "worldwide".\n\nIf we sign the wrong version, we are exposed to a claim. If we raise it now, it could trigger a re-negotiation spiral.\n\nMy recommendation: fix both silently in the execution version and flag to Jenny as "minor corrections to reflect agreed positions." Do NOT escalate to Kestrel\'s partners.',
    preview: 'Seven version differences found — two are substantive...',
    category: 'internal',
    state: 'unread',
    priority: 'urgent',
    timestamp: 'Week 44, Wednesday',
    responseOptions: [
      { id: 'r1', label: 'Agreed — correct silently and flag as housekeeping. No need to re-open negotiations.', effects: '+4 momentum, +3 reputation, -5 riskLevel', resourceEffects: { dealMomentum: 4, reputation: 3, riskLevel: -5 } },
      { id: 'r2', label: 'We need to flag both to Kestrel transparently — our integrity matters more than speed', effects: '-3 momentum, +5 reputation, -8 riskLevel', resourceEffects: { dealMomentum: -3, reputation: 5, riskLevel: -8 } },
      { id: 'r3', label: 'Fix the indemnity cap silently but flag the non-compete — that one could blow up post-closing', effects: '+2 momentum, +3 reputation, -4 riskLevel', resourceEffects: { dealMomentum: 2, reputation: 3, riskLevel: -4 } },
    ],
  },
  {
    id: 'email-113',
    week: 45,
    phase: 9,
    sender: 'Ricardo Mendes',
    senderRole: 'Founder & CEO, Solara Systems',
    subject: 'I need one more day to think',
    body: 'I know we are supposed to sign tomorrow. I know Kestrel is ready. I know everyone is waiting.\n\nBut I woke up at 3am and I cannot stop thinking — am I selling too early? Solara is growing 30% year on year. The technology roadmap is stronger than ever. Tomás just closed the Airbus pilot.\n\nWhat if the right move is to wait two more years and sell for twice the price?\n\nI am not saying I won\'t sign. I am saying I need you to look me in the eye and tell me this is the right decision. Not as my banker — as someone who has seen a hundred of these deals.\n\nCan we meet tomorrow morning before the signing?',
    preview: 'Client having last-minute doubts — wants reassurance before signing...',
    category: 'client',
    state: 'unread',
    priority: 'urgent',
    timestamp: 'Week 45, Wednesday',
    responseOptions: [
      { id: 'r1', label: 'I will be at your office at 7am. We will talk it through properly. This feeling is completely normal.', effects: '+10 trust, +3 momentum', resourceEffects: { clientTrust: 10, dealMomentum: 3 } },
      { id: 'r2', label: 'Ricardo — every seller feels this. The market window is open NOW. In two years, who knows. Let\'s not lose this.', effects: '+5 trust, +5 momentum, -2 reputation (pushy)', resourceEffects: { clientTrust: 5, dealMomentum: 5, reputation: -2 } },
      { id: 'r3', label: 'If you are not ready, we do not sign. I would rather delay than have you regret this in six months.', effects: '+12 trust, -8 momentum, +5 reputation', resourceEffects: { clientTrust: 12, dealMomentum: -8, reputation: 5 } },
    ],
  },
  {
    id: 'email-114',
    week: 45,
    phase: 9,
    sender: 'Ricardo Mendes',
    senderRole: 'Founder & CEO, Solara Systems',
    subject: 'Send the damn document',
    body: 'Okay. I am ready.\n\nI spoke to Helena this morning. She reminded me why we started this process — not because Solara is failing, but because we have built something valuable enough that someone wants to pay €120M for it. That is a win.\n\nSend the document. Let\'s get this done.\n\nOne thing — I want to sign in person, in the Solara boardroom. Not over DocuSign. This company deserves that.',
    preview: 'Client gives the green light — wants in-person signing...',
    category: 'client',
    state: 'unread',
    priority: 'urgent',
    timestamp: 'Week 45, Thursday',
    responseOptions: [
      { id: 'r1', label: 'Boardroom signing it is. I will have the execution copies there by 2pm. Congratulations, Ricardo.', effects: '+8 trust, +8 momentum, +3 morale', resourceEffects: { clientTrust: 8, dealMomentum: 8, morale: 3 } },
      { id: 'r2', label: 'In-person works. Let me coordinate with Kestrel — they may want their partners present too.', effects: '+5 trust, +5 momentum, +2 reputation', resourceEffects: { clientTrust: 5, dealMomentum: 5, reputation: 2 } },
    ],
  },
  {
    id: 'email-115',
    week: 46,
    phase: 9,
    sender: 'Jenny Li',
    senderRole: 'Paralegal, Kestrel Capital',
    subject: 'RE: Signing confirmation — all parties ready',
    body: 'Confirming the following on behalf of Kestrel Capital:\n\n1. Investment committee has given final approval.\n2. Fund counsel has cleared the execution version (v14.4 — reconciled).\n3. Escrow account is funded and release instruction is pre-authorised.\n4. Tom Hargreaves and Sarah Cheng will attend the signing in person.\n\nWe are ready to proceed at 2pm Friday as agreed. Please confirm seller-side attendees and ensure board resolutions are executed prior to the ceremony.\n\nLooking forward to closing this one out.',
    preview: 'Kestrel confirms — investment committee approved, escrow funded, ready to sign...',
    category: 'buyer',
    state: 'unread',
    priority: 'high',
    timestamp: 'Week 46, Wednesday',
    responseOptions: [
      { id: 'r1', label: 'Confirmed. Ricardo, Helena, and our team will be present. Board resolutions are executed. See you Friday.', effects: '+10 momentum, +5 reputation, +5 morale', resourceEffects: { dealMomentum: 10, reputation: 5, morale: 5 } },
      { id: 'r2', label: 'Confirmed. One final request — can we get written confirmation that there are no outstanding IC conditions?', effects: '+5 momentum, +3 reputation, -3 riskLevel', resourceEffects: { dealMomentum: 5, reputation: 3, riskLevel: -3 } },
    ],
  },
];

export const phase9Deliverables: Deliverable[] = [
  {
    id: 'del-90',
    name: 'Final Signed SPA',
    phase: 9,
    status: 'not_started',
    completion: 0,
    quality: 'adequate',
    dependencies: ['task-114'],
    deadline: 46,
  },
  {
    id: 'del-91',
    name: 'Closing Handover Pack',
    phase: 9,
    status: 'not_started',
    completion: 0,
    quality: 'adequate',
    dependencies: ['task-117', 'task-118'],
    deadline: 46,
  },
];

export const phase9Risks: Risk[] = [
  {
    id: 'risk-90',
    name: 'Document Version Desync',
    description: 'Seller counsel and buyer counsel are working from different document versions with substantive discrepancies. Signing the wrong version could create post-closing liability or trigger a dispute over agreed terms.',
    category: 'legal',
    severity: 'high',
    probability: 40,
    mitigated: false,
    surfacedWeek: 44,
    surfacedPhase: 9,
  },
  {
    id: 'risk-91',
    name: 'Client Last-Minute Hesitation',
    description: 'Ricardo experiences seller\'s remorse at the final moment — questioning whether Solara\'s growth trajectory justifies holding rather than selling. Could delay or derail signing if not managed with empathy and conviction.',
    category: 'client',
    severity: 'critical',
    probability: 40,
    mitigated: false,
    surfacedWeek: 45,
    surfacedPhase: 9,
  },
  {
    id: 'risk-92',
    name: 'Signing Ceremony Failure',
    description: 'Logistical or procedural failure during the signing ceremony itself — missing board resolutions, unfunded escrow, absent signatories, or a last-second markup demand. Any single point of failure can collapse the choreography.',
    category: 'timing',
    severity: 'high',
    probability: 25,
    mitigated: false,
    surfacedWeek: 46,
    surfacedPhase: 9,
  },
];

export const phase9Headlines: Headline[] = [
  { id: 'hl-90', week: 44, text: 'European industrial tech M&A hits record quarterly volume — deal windows narrowing fast.', category: 'macro' },
  { id: 'hl-91', week: 44, text: 'Kestrel Capital closes €2.1B Fund IV — dry powder for immediate deployment.', category: 'buyer_strategy' },
  { id: 'hl-92', week: 45, text: 'High-profile automation deal collapses at signing stage over unresolved warranty dispute.', category: 'comparable' },
  { id: 'hl-93', week: 46, text: 'Solara Systems wins Airbus innovation partnership — market validates technology platform.', category: 'sector' },
];
