// ============================================
// Phase 3: Market Outreach
// Teaser distribution, NDA processing, buyer engagement
// Weeks 15-20 — The deal goes external
// ============================================
export const phase3Tasks = [
    {
        id: 'task-40', name: 'Launch Tier 1 Teaser Outreach',
        description: 'Send the teaser to the 8 highest-priority targets — strategic industrials and top-tier PE. Controlled, confidential, and sequenced to manage response timing.',
        phase: 3, category: 'market', status: 'recommended', cost: 0, work: 5, complexity: 'low',
        effectSummary: 'Launches market process, +8 momentum',
        workstreamId: 'buyer_outreach',
    },
    {
        id: 'task-41', name: 'Launch Broader Outreach Wave',
        description: 'Extend the teaser to Tier 2 and Tier 3 targets — wider PE universe, infrastructure funds, and secondary strategics. Increases response volume but raises confidentiality exposure.',
        phase: 3, category: 'market', status: 'available', cost: 0, work: 10, complexity: 'low',
        effectSummary: 'Max response rate, +confidentiality risk',
        workstreamId: 'buyer_outreach',
    },
    {
        id: 'task-42', name: 'Process NDA Requests',
        description: 'Review and execute NDAs as buyer requests arrive. Legal bottleneck — each NDA requires review, potential redline negotiation, and counter-signing. Speed matters.',
        phase: 3, category: 'internal', status: 'locked', cost: 0, work: 12, complexity: 'medium',
        effectSummary: 'Converts interest to access, critical path',
        dependencies: ['task-40'],
    },
    {
        id: 'task-43', name: 'Grant CIM Access to Signed Buyers',
        description: 'Open data room access for buyers who have signed NDAs. Control access tiers — Tier 1 gets full CIM + model, Tier 2 gets CIM only.',
        phase: 3, category: 'internal', status: 'locked', cost: 0, work: 5, complexity: 'low',
        effectSummary: 'Moves buyers deeper into process',
        dependencies: ['task-42'],
    },
    {
        id: 'task-44', name: 'Follow Up with Silent Buyers',
        description: 'Re-engage Tier 1 targets who haven\'t responded. A polite nudge — but too aggressive and you look desperate.',
        phase: 3, category: 'relationship', status: 'locked', cost: 0, work: 8, complexity: 'medium',
        effectSummary: 'Second chance engagement, -2 momentum if too pushy',
        dependencies: ['task-40'],
    },
    {
        id: 'task-45', name: 'Schedule First Buyer Calls',
        description: 'Arrange introductory calls with the most engaged buyers. These are the first live conversations — buyers are assessing the asset and the advisory team.',
        phase: 3, category: 'relationship', status: 'locked', cost: 0, work: 10, complexity: 'medium',
        effectSummary: 'Deepens engagement, reveals buyer intent',
        dependencies: ['task-43'],
    },
    {
        id: 'task-46', name: 'Respond to Buyer Q&A Packs',
        description: 'Serious buyers send detailed question packs after reviewing the CIM. Each pack requires 15-25 hours of coordinated response involving the team and the client.',
        phase: 3, category: 'deliverable', status: 'locked', cost: 0, work: 20, complexity: 'high',
        effectSummary: 'Critical — quality of answers drives conviction',
        dependencies: ['task-43'],
    },
    {
        id: 'task-47', name: 'Tighten Confidentiality Controls',
        description: 'Monitor for leaks and tighten information flow. Restrict data room access logs, enforce NDA compliance, and address any rumour signals in the market.',
        phase: 3, category: 'internal', status: 'available', cost: 5, work: 8, complexity: 'low',
        effectSummary: '-10 risk level, protects client trust',
    },
    {
        id: 'task-48', name: 'Qualify Buyer Seriousness',
        description: 'Analyse data room access patterns, question quality, and engagement speed to determine which buyers are genuinely interested vs fishing for market intelligence.',
        phase: 3, category: 'strategic', status: 'locked', cost: 0, work: 10, complexity: 'medium',
        effectSummary: 'Separates real interest from noise',
        dependencies: ['task-43'],
    },
    {
        id: 'task-49', name: 'Client Update — Market Response',
        description: 'Brief Ricardo on the market\'s reaction to the teaser. Manage expectations — early silence doesn\'t mean failure. Frame the response quality, not just volume.',
        phase: 3, category: 'relationship', status: 'locked', cost: 0, work: 4, complexity: 'low',
        effectSummary: '+5 trust, manages client anxiety',
        dependencies: ['task-40'],
    },
    {
        id: 'task-50', name: 'Engage External Legal for NDA Surge',
        description: 'If NDA volume exceeds internal capacity, engage external counsel to process the overflow. Expensive but prevents bottleneck.',
        phase: 3, category: 'external_advisor', status: 'available', cost: 20, work: 0, complexity: 'low',
        effectSummary: 'Clears NDA backlog instantly, expensive',
    },
];
export const phase3Emails = [
    {
        id: 'email-40',
        week: 15,
        phase: 3,
        sender: 'Marcus Aldridge',
        senderRole: 'Managing Partner',
        subject: 'Market launch — controlled and deliberate',
        body: 'Materials are approved. Time to take this to market.\n\nRemember: this is a controlled auction, not a fire sale. Tier 1 strategics go first — they need more time to mobilise internally. PE follows 7-10 days later.\n\nI want a weekly update on:\n- Response rate by tier\n- NDA conversion\n- Any confidentiality flags\n\nGood luck. This is where our preparation pays off.',
        preview: 'Market launch approved — controlled approach...',
        category: 'partner',
        state: 'unread',
        priority: 'high',
        timestamp: 'Week 15, Monday',
        responseOptions: [
            { id: 'r1', label: 'Tier 1 teasers going out today. First responses expected by Wednesday.', effects: '+5 momentum', resourceEffects: { dealMomentum: 5 } },
            { id: 'r2', label: 'Agreed — I\'ll send a daily tracker once responses start flowing.', effects: '+3 reputation', resourceEffects: { reputation: 3 } },
        ],
    },
    {
        id: 'email-41',
        week: 15,
        phase: 3,
        sender: 'Ricardo Mendes',
        senderRole: 'Founder & CEO, Solara Systems',
        subject: 'We\'re really doing this',
        body: 'So the teaser goes out this week. I have to admit, it feels strange knowing strangers will be evaluating my company.\n\nA few things on my mind:\n- Confidentiality is paramount. If this leaks to our customers or competitors, it could seriously damage us.\n- I want to know who receives the teaser before it goes out. No surprises.\n- If Schneider is on the list, I want to be involved in how we approach them — I know their Head of Strategy personally.\n\nThis is a big step. Keep me close.',
        preview: 'Client nervous about market exposure...',
        category: 'client',
        state: 'unread',
        priority: 'high',
        timestamp: 'Week 15, Tuesday',
        responseOptions: [
            { id: 'r1', label: 'You\'ll see the full target list before anything goes out. Complete transparency.', effects: '+8 trust', resourceEffects: { clientTrust: 8 } },
            { id: 'r2', label: 'We\'ll handle Schneider with a personal approach through your contact. Smart move.', effects: '+5 trust, +3 momentum', resourceEffects: { clientTrust: 5, dealMomentum: 3 } },
            { id: 'r3', label: 'Trust the process — we\'ve done this many times. I\'ll flag anything unusual.', effects: '+3 trust, +3 reputation', resourceEffects: { clientTrust: 3, reputation: 3 } },
        ],
    },
    {
        id: 'email-42',
        week: 16,
        phase: 3,
        sender: 'James Wu',
        senderRole: 'Associate',
        subject: 'First responses in — mixed signals',
        body: 'Teaser response update after 5 business days:\n\n**Responded (4 of 8 Tier 1):**\n- Vektor Industries: Requesting NDA immediately. Very fast turnaround.\n- Kestrel Capital: "Interesting — please send NDA." Brief but positive.\n- Nexus Data Group: Long email asking 12 questions before they\'ll sign. Red flag or genuine diligence?\n- Frontier Equity: "We\'re tracking this sector. Please send the NDA and any preliminary financials."\n\n**Silent (4 of 8 Tier 1):**\n- Schneider Digital: Nothing yet. Could be internal routing delays.\n- 3 others: No response.\n\nVektor\'s speed is interesting — they may have been tracking Solara independently. Should we accelerate them?',
        preview: 'First teaser responses — 4 of 8 engaged...',
        category: 'internal',
        state: 'unread',
        priority: 'high',
        timestamp: 'Week 16, Monday',
        responseOptions: [
            { id: 'r1', label: 'Process Vektor and Kestrel NDAs immediately — they\'re the frontrunners', effects: '+5 momentum', resourceEffects: { dealMomentum: 5 } },
            { id: 'r2', label: 'Push Nexus to sign first, ask questions later — standard practice', effects: '+3 momentum, -2 reputation', resourceEffects: { dealMomentum: 3, reputation: -2 } },
            { id: 'r3', label: 'Wait for the full week before acting — I want to see Schneider\'s response', effects: '+3 reputation, -2 momentum (cautious)', resourceEffects: { reputation: 3, dealMomentum: -2 } },
        ],
    },
    {
        id: 'email-43',
        week: 16,
        phase: 3,
        sender: 'Ricardo Mendes',
        senderRole: 'Founder & CEO, Solara Systems',
        subject: 'Why hasn\'t Schneider responded?',
        body: 'It\'s been a week and Schneider hasn\'t said anything. Should I be worried?\n\nI spoke to Klaus (their Head of Strategy) at a conference last month and he seemed very interested in predictive maintenance. Maybe I should reach out directly?\n\nAlso — who is Vektor Industries? I\'ve never heard of them. Are they serious?',
        preview: 'Client anxious about Schneider silence, questioning Vektor...',
        category: 'client',
        state: 'unread',
        priority: 'normal',
        timestamp: 'Week 16, Wednesday',
        responseOptions: [
            { id: 'r1', label: 'Schneider is a large organisation — internal routing takes time. This is normal.', effects: '+5 trust (reassurance)', resourceEffects: { clientTrust: 5 } },
            { id: 'r2', label: 'Your personal contact with Klaus could help — let\'s coordinate a warm follow-up', effects: '+5 momentum, +3 trust', resourceEffects: { dealMomentum: 5, clientTrust: 3 } },
            { id: 'r3', label: 'Vektor is a €4B industrial automation group. They\'re very serious — and fast.', effects: '+3 trust, +3 momentum', resourceEffects: { clientTrust: 3, dealMomentum: 3 } },
        ],
    },
    {
        id: 'email-44',
        week: 17,
        phase: 3,
        sender: 'Ana Ferreira',
        senderRole: 'Vice President',
        subject: 'NDA surge — we need to talk about capacity',
        body: 'We now have 7 NDAs in various stages of processing:\n\n- 2 signed and returned (Vektor, Kestrel)\n- 3 with redlines pending review (Nexus, Frontier, one Tier 2 PE)\n- 2 just arrived (Schneider finally responded, plus a new strategic)\n\nThe redline negotiations are eating into our time. Nexus wants to remove the non-solicitation clause entirely. Frontier\'s counsel is demanding a mutual NDA with ridiculous indemnity terms.\n\nI can handle 3-4 NDAs per week internally, but we\'re at 7. Either we bring in external legal support (€15-20k) or we slow-walk some of the lower priority ones.\n\nWhat\'s your call?',
        preview: 'NDA processing bottleneck — capacity crunch...',
        category: 'internal',
        state: 'unread',
        priority: 'high',
        timestamp: 'Week 17, Tuesday',
        responseOptions: [
            { id: 'r1', label: 'Bring in external counsel — we can\'t afford to lose momentum on NDAs', effects: '-20 budget, +8 momentum', resourceEffects: { budget: -20, dealMomentum: 8 } },
            { id: 'r2', label: 'Prioritise Schneider and Nexus — slow-walk the lower tiers', effects: '+3 momentum, -2 reputation (selective)', resourceEffects: { dealMomentum: 3, reputation: -2 } },
            { id: 'r3', label: 'Push back on unreasonable redlines — standard NDA or no access', effects: '+5 reputation, -3 momentum (some may walk)', resourceEffects: { reputation: 5, dealMomentum: -3 } },
        ],
    },
    {
        id: 'email-45',
        week: 18,
        phase: 3,
        sender: 'Sofia Lindqvist',
        senderRole: 'Analyst',
        subject: 'Data room access log — interesting patterns',
        body: 'Access report for the first week of CIM distribution:\n\n**High engagement:**\n- Vektor Industries: 14 hours total, downloaded financial model, viewed customer analysis 3x\n- Kestrel Capital: 8 hours, focused on revenue bridge and working capital\n\n**Moderate:**\n- Frontier Equity: 3 hours, mostly executive summary and market section\n\n**Low/Concerning:**\n- Nexus Data Group: 45 minutes total. Downloaded the CIM PDF and nothing else.\n\n**Not yet accessed:**\n- Schneider Digital: NDA just signed, access granted yesterday\n\nVektor\'s level of engagement is exceptional — they\'re doing serious analytical work. Nexus is either very efficient or not interested.',
        preview: 'Data room analytics reveal buyer engagement levels...',
        category: 'internal',
        state: 'unread',
        priority: 'normal',
        timestamp: 'Week 18, Monday',
        responseOptions: [
            { id: 'r1', label: 'Schedule a call with Vektor this week — capitalise on their enthusiasm', effects: '+5 momentum, +3 trust', resourceEffects: { dealMomentum: 5, clientTrust: 3 } },
            { id: 'r2', label: 'Reach out to Nexus — find out if they need guidance or have lost interest', effects: '+3 momentum', resourceEffects: { dealMomentum: 3 } },
            { id: 'r3', label: 'Let it develop — it\'s too early to draw conclusions from access patterns', effects: '+3 reputation', resourceEffects: { reputation: 3 } },
        ],
    },
    {
        id: 'email-46',
        week: 18,
        phase: 3,
        sender: 'Ricardo Mendes',
        senderRole: 'Founder & CEO, Solara Systems',
        subject: 'Three NDAs in — is that good?',
        body: 'Helena tells me three buyers have signed NDAs and are in the data room. Is that a lot? Is that few?\n\nI keep reading articles about deals with 20 interested parties. Should we be going broader?\n\nAlso — I bumped into a friend who runs a family office in Zurich. He said he\'d be interested in looking at Solara. Should I connect him with your team?',
        preview: 'Client benchmarking response rate, proposing new buyer...',
        category: 'client',
        state: 'unread',
        priority: 'normal',
        timestamp: 'Week 18, Thursday',
        responseOptions: [
            { id: 'r1', label: 'Three serious buyers is better than twenty tourists. Quality over quantity.', effects: '+5 trust', resourceEffects: { clientTrust: 5 } },
            { id: 'r2', label: 'We have more coming — Schneider just signed. The process is healthy.', effects: '+5 trust, +3 momentum', resourceEffects: { clientTrust: 5, dealMomentum: 3 } },
            { id: 'r3', label: 'Happy to look at the family office — send me the details and we\'ll qualify them', effects: '+3 trust, +2 momentum', resourceEffects: { clientTrust: 3, dealMomentum: 2 } },
        ],
    },
    {
        id: 'email-47',
        week: 19,
        phase: 3,
        sender: 'James Wu',
        senderRole: 'Associate',
        subject: 'Q&A pack from Vektor — 47 questions',
        body: 'Vektor just sent their initial Q&A pack. 47 questions across:\n- Financial performance (18 questions)\n- Technology and IP (12 questions)\n- Customer retention and churn (8 questions)\n- Management and key personnel (5 questions)\n- Regulatory and compliance (4 questions)\n\nThis is serious diligence-level questioning at the CIM stage — unusual but very positive. They\'re clearly building an internal investment case.\n\nEstimated effort to respond properly: 20-25 hours across the team, plus we\'ll need input from Helena and Tomás on some technical questions.\n\nShould we prioritise this over the other buyers\' requests?',
        preview: 'Major Q&A pack from top buyer — resource allocation decision...',
        category: 'internal',
        state: 'unread',
        priority: 'high',
        timestamp: 'Week 19, Monday',
        responseOptions: [
            { id: 'r1', label: 'All hands on Vektor — they\'re the frontrunner and deserve our best', effects: '+8 momentum, -3 capacity drain', resourceEffects: { dealMomentum: 8 } },
            { id: 'r2', label: 'Balanced approach — answer Vektor\'s top 20 first, keep other buyers progressing', effects: '+5 momentum, +3 reputation', resourceEffects: { dealMomentum: 5, reputation: 3 } },
            { id: 'r3', label: 'Standard timeline for all buyers — we can\'t show favouritism at this stage', effects: '+5 reputation, -3 momentum', resourceEffects: { reputation: 5, dealMomentum: -3 } },
        ],
    },
    {
        id: 'email-48',
        week: 20,
        phase: 3,
        sender: 'Marcus Aldridge',
        senderRole: 'Managing Partner',
        subject: 'Process checkpoint — are we ready to move to shortlist?',
        body: 'Where do we stand? I need a clear picture:\n\n1. How many buyers have meaningful engagement?\n2. Who are the top 3-4 we\'d want in the NBO round?\n3. Any surprises — positive or negative?\n4. Is the client aligned on next steps?\n\nThe market window won\'t stay open forever. If we have genuine competitive tension, it\'s time to start funnelling toward indicative offers.',
        preview: 'Partner wants process assessment for shortlist phase...',
        category: 'partner',
        state: 'unread',
        priority: 'high',
        timestamp: 'Week 20, Monday',
        responseOptions: [
            { id: 'r1', label: 'We have strong competitive tension — ready to move to shortlist and NBO', effects: '+8 momentum, +3 trust', resourceEffects: { dealMomentum: 8, clientTrust: 3 } },
            { id: 'r2', label: 'Need one more week — Schneider is warming up and I don\'t want to lose them', effects: '+3 reputation, -2 momentum', resourceEffects: { reputation: 3, dealMomentum: -2 } },
        ],
    },
];
export const phase3Deliverables = [
    {
        id: 'del-30',
        name: 'Buyer Engagement Tracker',
        phase: 3,
        status: 'not_started',
        completion: 0,
        quality: 'adequate',
        dependencies: ['task-40'],
    },
    {
        id: 'del-31',
        name: 'Q&A Response Package',
        phase: 3,
        status: 'not_started',
        completion: 0,
        quality: 'adequate',
        dependencies: ['task-46'],
    },
];
export const phase3Risks = [
    {
        id: 'risk-30',
        name: 'Confidentiality Breach',
        description: 'The wider the outreach, the higher the risk of a leak. If Solara\'s sale process becomes public, it could spook customers and competitors.',
        category: 'market',
        severity: 'high',
        probability: 20,
        mitigated: false,
        surfacedWeek: 15,
        surfacedPhase: 3,
    },
    {
        id: 'risk-31',
        name: 'NDA Processing Bottleneck',
        description: 'Too many NDAs arriving simultaneously could overwhelm the team, creating delays that cool buyer interest.',
        category: 'team',
        severity: 'medium',
        probability: 40,
        mitigated: false,
        surfacedWeek: 15,
        surfacedPhase: 3,
    },
    {
        id: 'risk-32',
        name: 'Low Response Rate',
        description: 'If fewer than 3 buyers engage seriously, the process lacks competitive tension and valuation leverage collapses.',
        category: 'market',
        severity: 'high',
        probability: 25,
        mitigated: false,
        surfacedWeek: 16,
        surfacedPhase: 3,
    },
];
export const phase3Headlines = [
    { id: 'hl-30', week: 15, text: 'Infrastructure tech M&A pipeline builds as year-end dealmaking accelerates.', category: 'sector' },
    { id: 'hl-31', week: 16, text: 'PE firms sitting on record dry powder seek industrial software platforms.', category: 'macro' },
    { id: 'hl-32', week: 17, text: 'Rival predictive maintenance startup raises €40M Series C at 18x revenue.', category: 'comparable' },
    { id: 'hl-33', week: 18, text: 'Cross-border M&A deal timelines extending as regulatory scrutiny increases.', category: 'regulatory' },
    { id: 'hl-34', week: 19, text: 'Strategic acquirers paying 25-30% premium over PE in contested tech auctions.', category: 'comparable' },
    { id: 'hl-35', week: 20, text: 'Mid-market advisory firms report highest win rates when process launches in Q2-Q3.', category: 'sector' },
];
//# sourceMappingURL=phase3.js.map