import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useGameStore } from '../store/gameStore';
import { MITIGATION_ACTIONS } from '../config/phaseBudgets';
import { AlertTriangle, Users, Zap, CheckCircle } from 'lucide-react';
export default function CompetitorMitigationPanel() {
    const competitorThreats = useGameStore((s) => s.competitorThreats);
    const resources = useGameStore((s) => s.resources);
    const executeMitigationAction = useGameStore((s) => s.executeMitigationAction);
    const activeThreats = competitorThreats.filter((t) => !t.resolved);
    if (activeThreats.length === 0)
        return null;
    const relationshipActions = MITIGATION_ACTIONS.filter((a) => a.category === 'relationship');
    const processActions = MITIGATION_ACTIONS.filter((a) => a.category === 'process');
    return (_jsxs("div", { className: "rounded-[var(--radius-lg)] border border-red-500/30 bg-red-500/5 overflow-hidden", children: [_jsxs("div", { className: "flex items-center gap-2.5 px-4 py-3 border-b border-red-500/20 bg-red-500/10", children: [_jsx(AlertTriangle, { size: 15, className: "text-red-400 shrink-0" }), _jsxs("div", { children: [_jsx("h3", { className: "text-[13px] font-semibold text-red-300", children: "Competing Advisor Detected" }), _jsxs("p", { className: "text-[11px] text-red-400/70 mt-0.5", children: [activeThreats.map((t) => t.advisorName).join(', '), " ", activeThreats.length === 1 ? 'is' : 'are', " in discussions with ", ' ', useGameStore.getState().client.name] })] })] }), _jsx("div", { className: "p-4 space-y-4", children: activeThreats.map((threat) => (_jsxs("div", { className: "space-y-3", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-1.5 text-[10px] font-semibold text-text-muted uppercase tracking-widest mb-2", children: [_jsx(Users, { size: 10 }), "Relationship Accelerators"] }), _jsx("div", { className: "grid grid-cols-1 gap-2", children: relationshipActions.map((action) => {
                                        const used = threat.usedActions.includes(action.id);
                                        const canAfford = resources.budget >= action.budgetCost;
                                        return (_jsxs("div", { className: `flex items-center justify-between p-3 rounded-[var(--radius-md)] border transition-all ${used ? 'border-green-500/30 bg-green-500/5 opacity-70' :
                                                canAfford ? 'border-border-subtle bg-bg-primary hover:border-accent-primary/30' :
                                                    'border-border-subtle/40 bg-bg-primary/50 opacity-50'}`, children: [_jsxs("div", { children: [_jsx("p", { className: "text-[12px] font-medium text-text-secondary", children: action.label }), _jsxs("div", { className: "flex items-center gap-2 mt-0.5 text-[10px] text-text-muted", children: [action.effects.clientTrust && _jsxs("span", { className: "text-green-400", children: ["+", action.effects.clientTrust, " trust"] }), action.effects.dealMomentum && _jsxs("span", { className: "text-blue-400", children: ["+", action.effects.dealMomentum, " momentum"] }), action.effects.reputation && _jsxs("span", { className: "text-purple-400", children: ["+", action.effects.reputation, " reputation"] })] })] }), _jsxs("div", { className: "flex items-center gap-2 ml-3 shrink-0", children: [action.budgetCost > 0 && (_jsxs("span", { className: `text-[10px] font-mono ${canAfford ? 'text-text-muted' : 'text-red-400'}`, children: ["\u20AC", action.budgetCost, "k"] })), used ? (_jsx(CheckCircle, { size: 14, className: "text-green-400" })) : (_jsx("button", { onClick: () => executeMitigationAction(threat.id, action.id), disabled: !canAfford, className: "text-[10px] font-medium py-1 px-2.5 rounded-[var(--radius-sm)] border border-accent-primary/30 text-accent-primary hover:bg-accent-soft transition-colors disabled:opacity-40 disabled:cursor-not-allowed", children: "Execute" }))] })] }, action.id));
                                    }) })] }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-1.5 text-[10px] font-semibold text-text-muted uppercase tracking-widest mb-2", children: [_jsx(Zap, { size: 10 }), "Process Accelerators"] }), _jsx("div", { className: "grid grid-cols-1 gap-2", children: processActions.map((action) => {
                                        const used = threat.usedActions.includes(action.id);
                                        const canAfford = resources.budget >= action.budgetCost;
                                        return (_jsxs("div", { className: `flex items-center justify-between p-3 rounded-[var(--radius-md)] border transition-all ${used ? 'border-green-500/30 bg-green-500/5 opacity-70' :
                                                canAfford ? 'border-border-subtle bg-bg-primary hover:border-accent-primary/30' :
                                                    'border-border-subtle/40 bg-bg-primary/50 opacity-50'}`, children: [_jsxs("div", { children: [_jsx("p", { className: "text-[12px] font-medium text-text-secondary", children: action.label }), _jsx("p", { className: "text-[10px] text-text-muted mt-0.5", children: action.description }), _jsxs("div", { className: "flex items-center gap-2 mt-0.5 text-[10px]", children: [action.effects.pitchWeeksReduced && (_jsxs("span", { className: "text-yellow-400", children: ["\u2212", action.effects.pitchWeeksReduced, " weeks"] })), action.effects.dealMomentum && _jsxs("span", { className: "text-blue-400", children: ["+", action.effects.dealMomentum, " momentum"] })] })] }), _jsxs("div", { className: "flex items-center gap-2 ml-3 shrink-0", children: [action.budgetCost > 0 && (_jsxs("span", { className: `text-[10px] font-mono ${canAfford ? 'text-text-muted' : 'text-red-400'}`, children: ["\u20AC", action.budgetCost, "k"] })), used ? (_jsx(CheckCircle, { size: 14, className: "text-green-400" })) : (_jsx("button", { onClick: () => executeMitigationAction(threat.id, action.id), disabled: !canAfford, className: "text-[10px] font-medium py-1 px-2.5 rounded-[var(--radius-sm)] border border-yellow-500/30 text-yellow-400 hover:bg-yellow-500/10 transition-colors disabled:opacity-40 disabled:cursor-not-allowed", children: "Execute" }))] })] }, action.id));
                                    }) })] })] }, threat.id))) })] }));
}
//# sourceMappingURL=CompetitorMitigationPanel.js.map