import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useGameStore } from '../store/gameStore';
import { STAFF_PROFILES, CONTRACTOR_PROFILES } from '../config/phaseBudgets';
import { X, Users, Zap, AlertTriangle } from 'lucide-react';
export default function StaffingModal({ onClose }) {
    const [tab, setTab] = useState('permanent');
    const resources = useGameStore((s) => s.resources);
    const tasks = useGameStore((s) => s.tasks);
    const tempAllocations = useGameStore((s) => s.tempCapacityAllocations);
    const hireStaffer = useGameStore((s) => s.hireStaffer);
    const allocateTempCapacity = useGameStore((s) => s.allocateTempCapacity);
    const releaseTempCapacity = useGameStore((s) => s.releaseTempCapacity);
    const [selectedTask, setSelectedTask] = useState('');
    const [hiredProfile, setHiredProfile] = useState(null);
    const eligibleTasks = tasks.filter((t) => t.status === 'in_progress' || t.status === 'available' || t.status === 'recommended');
    return (_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm", children: _jsxs("div", { className: "bg-bg-secondary border border-border-subtle rounded-[var(--radius-lg)] shadow-[var(--shadow-heavy)] w-full max-w-2xl mx-4 overflow-hidden flex flex-col max-h-[90vh]", children: [_jsxs("div", { className: "flex items-center justify-between px-6 py-4 border-b border-border-subtle shrink-0", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-[15px] font-semibold text-text-primary", children: "Staffing & Capacity" }), _jsxs("p", { className: "text-[12px] text-text-muted mt-0.5", children: ["Budget available: ", _jsxs("span", { className: "font-mono text-text-accent", children: ["\u20AC", resources.budget, "k"] })] })] }), _jsx("button", { onClick: onClose, className: "p-1.5 rounded-[var(--radius-md)] hover:bg-surface-hover text-text-muted hover:text-text-primary transition-colors", children: _jsx(X, { size: 16 }) })] }), _jsx("div", { className: "flex border-b border-border-subtle px-6 shrink-0", children: ['permanent', 'temporary'].map((t) => (_jsx("button", { onClick: () => setTab(t), className: `py-3 px-4 text-[12px] font-medium border-b-2 -mb-px transition-colors ${tab === t
                            ? 'border-accent-primary text-text-accent'
                            : 'border-transparent text-text-muted hover:text-text-secondary'}`, children: t === 'permanent' ? (_jsxs("span", { className: "flex items-center gap-1.5", children: [_jsx(Users, { size: 12 }), " Permanent Hire"] })) : (_jsxs("span", { className: "flex items-center gap-1.5", children: [_jsx(Zap, { size: 12 }), " Temporary Capacity"] })) }, t))) }), _jsxs("div", { className: "overflow-y-auto flex-1 p-6", children: [tab === 'permanent' && (_jsxs("div", { className: "space-y-3", children: [_jsx("p", { className: "text-[12px] text-text-muted mb-4", children: "Permanent hires join your team for the rest of the engagement. One-off cost deducted from budget immediately." }), STAFF_PROFILES.map((profile) => {
                                    const canAfford = resources.budget >= profile.hireCost;
                                    const isHired = hiredProfile === profile.id;
                                    return (_jsxs("div", { className: `p-4 rounded-[var(--radius-md)] border transition-all ${isHired ? 'border-green-500/40 bg-green-500/5' :
                                            canAfford ? 'border-border-subtle hover:border-accent-primary/30 bg-bg-primary cursor-pointer' :
                                                'border-border-subtle/50 bg-bg-primary/50 opacity-60'}`, onClick: () => canAfford && !isHired && null, children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { children: [_jsx("h4", { className: "text-[13px] font-semibold text-text-primary", children: profile.label }), _jsxs("p", { className: "text-[11px] text-text-muted mt-0.5 capitalize", children: [profile.seniority, " \u00B7 ", profile.skills.join(', ')] })] }), _jsxs("div", { className: "text-right", children: [_jsxs("span", { className: "font-mono font-semibold text-[13px] text-text-accent", children: ["\u20AC", profile.hireCost, "k"] }), _jsx("p", { className: "text-[10px] text-text-muted mt-0.5", children: "one-off" })] })] }), _jsxs("div", { className: "flex items-center justify-between mt-3", children: [_jsxs("span", { className: "text-[11px] text-text-muted", children: ["+", profile.capacityBoost, " capacity"] }), !canAfford ? (_jsxs("span", { className: "text-[11px] text-red-400 flex items-center gap-1", children: [_jsx(AlertTriangle, { size: 10 }), " Insufficient budget"] })) : isHired ? (_jsx("span", { className: "text-[11px] text-green-400", children: "\u2713 Hired" })) : (_jsx("button", { onClick: () => { hireStaffer(profile.id); setHiredProfile(profile.id); }, className: "text-[11px] font-medium text-accent-primary hover:text-accent-primary/80 transition-colors py-1 px-2.5 rounded-[var(--radius-sm)] border border-accent-primary/30 hover:bg-accent-soft", children: "Hire" }))] })] }, profile.id));
                                })] })), tab === 'temporary' && (_jsxs("div", { className: "space-y-4", children: [_jsx("p", { className: "text-[12px] text-text-muted", children: "Contractors are allocated to a specific task. Higher weekly cost, but much faster execution. Released automatically when the task completes." }), _jsxs("div", { children: [_jsx("label", { className: "block text-[12px] font-medium text-text-secondary mb-1.5", children: "Target task" }), _jsxs("select", { value: selectedTask, onChange: (e) => setSelectedTask(e.target.value), className: "w-full bg-bg-primary border border-border-subtle rounded-[var(--radius-md)] px-3 py-2 text-[13px] text-text-primary focus:outline-none focus:border-accent-primary/50", children: [_jsx("option", { value: "", children: "\u2014 Select a task \u2014" }), eligibleTasks.map((t) => (_jsxs("option", { value: t.id, children: [t.name, " (", t.status, ")"] }, t.id)))] })] }), _jsx("div", { className: "space-y-3", children: CONTRACTOR_PROFILES.map((profile) => {
                                        const alreadyAllocated = tempAllocations.some((a) => a.taskId === selectedTask && a.profile === profile.id);
                                        return (_jsxs("div", { className: "p-4 rounded-[var(--radius-md)] border border-border-subtle bg-bg-primary", children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { children: [_jsx("h4", { className: "text-[13px] font-semibold text-text-primary", children: profile.label }), _jsx("p", { className: "text-[11px] text-text-muted mt-0.5", children: profile.description })] }), _jsxs("div", { className: "text-right ml-4 shrink-0", children: [_jsxs("span", { className: "font-mono font-semibold text-[13px] text-text-accent", children: ["\u20AC", profile.weeklyRate, "k"] }), _jsx("p", { className: "text-[10px] text-text-muted mt-0.5", children: "/week" })] })] }), _jsxs("div", { className: "flex items-center justify-between mt-3", children: [_jsxs("span", { className: "text-[11px] text-text-muted flex items-center gap-1", children: [_jsx(Zap, { size: 10, className: "text-yellow-400" }), "\u00D7", profile.speedMultiplier, " speed"] }), !selectedTask ? (_jsx("span", { className: "text-[11px] text-text-muted/60", children: "Select a task first" })) : alreadyAllocated ? (_jsx("span", { className: "text-[11px] text-green-400", children: "Already allocated" })) : (_jsx("button", { onClick: () => allocateTempCapacity(selectedTask, profile.id), className: "text-[11px] font-medium text-accent-primary hover:text-accent-primary/80 transition-colors py-1 px-2.5 rounded-[var(--radius-sm)] border border-accent-primary/30 hover:bg-accent-soft", children: "Allocate" }))] })] }, profile.id));
                                    }) }), tempAllocations.length > 0 && (_jsxs("div", { children: [_jsx("h3", { className: "text-[12px] font-semibold text-text-muted uppercase tracking-widest mb-2 mt-4", children: "Active Contractors" }), tempAllocations.map((a) => {
                                            const task = tasks.find((t) => t.id === a.taskId);
                                            const profile = CONTRACTOR_PROFILES.find((p) => p.id === a.profile);
                                            return (_jsxs("div", { className: "flex items-center justify-between py-2.5 border-b border-border-subtle/50 last:border-0", children: [_jsxs("div", { children: [_jsx("p", { className: "text-[12px] text-text-secondary", children: profile?.label }), _jsxs("p", { className: "text-[11px] text-text-muted", children: [task?.name ?? a.taskId, " \u00B7 \u20AC", a.weeklyRate, "k/week"] })] }), _jsx("button", { onClick: () => releaseTempCapacity(a.id), className: "text-[11px] text-red-400 hover:text-red-300 transition-colors py-1 px-2 rounded-[var(--radius-sm)] border border-red-500/20 hover:bg-red-500/10", children: "Release" })] }, a.id));
                                        })] }))] }))] })] }) }));
}
//# sourceMappingURL=StaffingModal.js.map