import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { useGameStore } from '../store/gameStore';
import StatusChip from './ui/StatusChip';
import ProgressBar from './ui/ProgressBar';
import { CheckCircle2, Clock, AlertTriangle, TrendingUp, TrendingDown, ArrowRight, X, Users, Zap, Sparkles, XCircle } from 'lucide-react';
export default function WeekSummaryOverlay() {
    const result = useGameStore((s) => s.lastWeekResult);
    const day = useGameStore((s) => s.day);
    const week = useGameStore((s) => s.week);
    const resources = useGameStore((s) => s.resources);
    const phaseGate = useGameStore((s) => s.phaseGate);
    const buyers = useGameStore((s) => s.buyers);
    const dismiss = useGameStore((s) => s.dismissWeekSummary);
    const advancePhase = useGameStore((s) => s.advancePhase);
    if (!result)
        return null;
    const hasCompleted = result.tasksCompleted.length > 0;
    const hasProgressed = result.tasksProgressed.length > 0;
    const hasBuyerChanges = result.buyerChanges.length > 0;
    const hasEvents = result.newEvents.length > 0;
    const hasCriticals = result.criticalOutcomes && result.criticalOutcomes.length > 0;
    return (_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center bg-bg-primary/80 backdrop-blur-sm", children: _jsxs("div", { className: "bg-bg-panel border border-border-subtle rounded-[var(--radius-lg)] shadow-[var(--shadow-elevated)] w-full max-w-xl max-h-[85vh] overflow-y-auto", children: [_jsxs("div", { className: "flex items-center justify-between p-5 border-b border-border-subtle", children: [_jsxs("div", { children: [_jsxs("div", { className: "text-[10px] font-mono uppercase tracking-widest text-text-muted", children: [result?.daysAdvanced === 1 ? '1 Day Advanced' : `${result?.daysAdvanced ?? '?'} Days Advanced`, _jsxs("span", { className: "ml-2 text-text-muted/50", children: ["\u00B7 Day ", day, " \u00B7 Week ", week] })] }), _jsx("h2", { className: "text-lg font-display font-semibold text-text-primary mt-1", children: "Situation Report" })] }), _jsx("button", { onClick: dismiss, className: "p-1.5 rounded-[var(--radius-sm)] hover:bg-surface-hover transition-colors", children: _jsx(X, { size: 16, className: "text-text-muted" }) })] }), _jsx("div", { className: "px-5 py-4 border-b border-border-subtle", children: _jsx("p", { className: "text-[13px] text-text-secondary leading-relaxed", children: result.narrativeSummary }) }), (hasCompleted || hasProgressed) && (_jsxs("div", { className: "px-5 py-4 border-b border-border-subtle space-y-3", children: [_jsx("div", { className: "text-[10px] font-mono uppercase tracking-widest text-text-muted", children: "Task Progress" }), result.tasksCompleted.map((t) => (_jsxs("div", { className: "flex items-center gap-3 p-2 rounded-[var(--radius-md)] bg-state-success/10", children: [_jsx(CheckCircle2, { size: 14, className: "text-state-success shrink-0" }), _jsx("span", { className: "text-[12px] text-text-primary", children: t.name }), _jsx(StatusChip, { label: "Completed", variant: "success" })] }, t.id))), result.tasksProgressed.map((t) => (_jsxs("div", { className: "flex items-center gap-3 p-2 rounded-[var(--radius-md)] bg-surface-default", children: [_jsx(Clock, { size: 14, className: "text-text-muted shrink-0" }), _jsx("span", { className: "text-[12px] text-text-secondary", children: t.name }), _jsx(StatusChip, { label: "In Progress", variant: "info" })] }, t.id)))] })), hasCriticals && (_jsxs("div", { className: "px-5 py-4 border-b border-border-subtle space-y-2", children: [_jsx("div", { className: "text-[10px] font-mono uppercase tracking-widest text-text-muted", children: "Exceptional Outcomes" }), result.criticalOutcomes.map((crit, i) => (_jsxs("div", { className: `flex items-start gap-3 p-3 rounded-[var(--radius-md)] border ${crit.type === 'success'
                                ? 'bg-state-success/10 border-state-success/25'
                                : 'bg-state-danger/10 border-state-danger/20'}`, children: [crit.type === 'success'
                                    ? _jsx(Sparkles, { size: 14, className: "text-state-success shrink-0 mt-0.5" })
                                    : _jsx(XCircle, { size: 14, className: "text-state-danger shrink-0 mt-0.5" }), _jsxs("div", { children: [_jsxs("div", { className: `text-[12px] font-semibold ${crit.type === 'success' ? 'text-state-success' : 'text-state-danger'}`, children: [crit.type === 'success' ? 'Exceptional: ' : 'Setback: ', crit.taskName] }), _jsx("p", { className: "text-[11px] text-text-secondary mt-1", children: crit.description })] })] }, i)))] })), result.hiddenWorkload && (_jsx("div", { className: "px-5 py-4 border-b border-border-subtle", children: _jsxs("div", { className: "flex items-start gap-3 p-3 rounded-[var(--radius-md)] bg-state-warning/10 border border-state-warning/20", children: [_jsx(AlertTriangle, { size: 16, className: "text-state-warning shrink-0 mt-0.5" }), _jsxs("div", { children: [_jsx("div", { className: "text-[12px] font-semibold text-text-primary", children: "Complication" }), _jsx("p", { className: "text-[11px] text-text-secondary mt-1", children: result.hiddenWorkload.description }), _jsxs("p", { className: "text-[10px] font-mono text-text-muted mt-1", children: ["+", result.hiddenWorkload.extraWork, "h extra work"] })] })] }) })), hasBuyerChanges && (_jsxs("div", { className: "px-5 py-4 border-b border-border-subtle space-y-3", children: [_jsx("div", { className: "text-[10px] font-mono uppercase tracking-widest text-text-muted", children: "Buyer Activity" }), result.buyerChanges.map((change, i) => {
                            const buyer = buyers.find((b) => b.id === change.buyerId);
                            const label = change.field === 'status'
                                ? `${change.from} → ${change.to}`
                                : `Interest: ${change.from} → ${change.to}`;
                            return (_jsxs("div", { className: "flex items-center gap-3 p-2 rounded-[var(--radius-md)] bg-accent-primary/5", children: [_jsx(Users, { size: 14, className: "text-accent-primary shrink-0" }), _jsx("span", { className: "text-[12px] text-text-primary", children: buyer?.name ?? change.buyerId }), _jsx(StatusChip, { label: label, variant: change.field === 'status' ? 'accent' : 'info' })] }, i));
                        })] })), hasEvents && (_jsxs("div", { className: "px-5 py-4 border-b border-border-subtle space-y-3", children: [_jsx("div", { className: "text-[10px] font-mono uppercase tracking-widest text-text-muted", children: "Events" }), result.newEvents.map((evt) => (_jsxs("div", { className: "flex items-start gap-3 p-3 rounded-[var(--radius-md)] bg-accent-primary/5 border border-accent-primary/10", children: [_jsx(Zap, { size: 14, className: "text-accent-primary shrink-0 mt-0.5" }), _jsxs("div", { children: [_jsx("div", { className: "text-[12px] font-semibold text-text-primary", children: evt.title }), _jsx("p", { className: "text-[11px] text-text-secondary mt-1", children: evt.description })] })] }, evt.id)))] })), _jsxs("div", { className: "px-5 py-4 border-b border-border-subtle", children: [_jsx("div", { className: "text-[10px] font-mono uppercase tracking-widest text-text-muted mb-3", children: "Resources" }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-3", children: [
                                { label: 'Budget', value: `€${resources.budget}k`, max: resources.budgetMax, current: resources.budget, color: 'accent' },
                                { label: 'Capacity', value: `${resources.teamCapacity}%`, max: 100, current: resources.teamCapacity, color: 'success' },
                                { label: 'Momentum', value: resources.dealMomentum, max: 100, current: resources.dealMomentum, color: 'accent' },
                                { label: 'Trust', value: resources.clientTrust, max: 100, current: resources.clientTrust, color: 'info' },
                            ].map((r) => (_jsxs("div", { className: "space-y-1", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-[11px] text-text-secondary", children: r.label }), _jsx("span", { className: "text-[11px] font-mono text-text-primary", children: r.value })] }), _jsx(ProgressBar, { value: Math.round((r.current / r.max) * 100), color: r.color, size: "sm" })] }, r.label))) }), _jsxs("div", { className: "flex items-center gap-4 mt-3 text-[11px]", children: [_jsxs("span", { className: "flex items-center gap-1 text-text-secondary", children: ["Morale: ", _jsx("span", { className: "font-mono text-text-primary", children: resources.morale }), resources.morale >= 70 ? _jsx(TrendingUp, { size: 12, className: "text-state-success" }) : _jsx(TrendingDown, { size: 12, className: "text-state-danger" })] }), _jsxs("span", { className: "flex items-center gap-1 text-text-secondary", children: ["Risk: ", _jsx("span", { className: "font-mono text-text-primary", children: resources.riskLevel })] })] })] }), phaseGate && (_jsxs("div", { className: "px-5 py-4 border-b border-border-subtle", children: [_jsx("div", { className: "text-[10px] font-mono uppercase tracking-widest text-text-muted mb-3", children: "Phase Gate" }), _jsx("div", { className: "space-y-2", children: phaseGate.requirements.map((req) => (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: `w-2 h-2 rounded-full ${req.met ? 'bg-state-success' : 'bg-border-subtle'}` }), _jsx("span", { className: `text-[11px] ${req.met ? 'text-text-primary' : 'text-text-muted'}`, children: req.label })] }, req.label))) }), phaseGate.canTransition && (_jsxs("button", { onClick: () => { advancePhase(); dismiss(); }, className: "mt-4 w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-accent-primary hover:bg-accent-hover text-white text-[13px] font-semibold rounded-[var(--radius-md)] transition-colors shadow-[var(--shadow-glow-strong)]", children: ["Advance to Next Phase", _jsx(ArrowRight, { size: 14 })] }))] })), _jsx("div", { className: "p-5", children: _jsx("button", { onClick: dismiss, className: "w-full px-4 py-2.5 text-[13px] font-medium text-text-secondary border border-border-subtle rounded-[var(--radius-md)] hover:bg-surface-hover transition-colors", children: "Continue" }) })] }) }));
}
//# sourceMappingURL=WeekSummaryOverlay.js.map